/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "analog_keymap.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(zmk_analog_keymap_Request, zmk_analog_keymap_Request, 2)


PB_BIND(zmk_analog_keymap_Response, zmk_analog_keymap_Response, 2)


PB_BIND(zmk_analog_keymap_AnalogKeymap, zmk_analog_keymap_AnalogKeymap, AUTO)


PB_BIND(zmk_analog_keymap_AnalogLayer, zmk_analog_keymap_AnalogLayer, AUTO)


PB_BIND(zmk_analog_keymap_AnalogBehaviorBinding, zmk_analog_keymap_AnalogBehaviorBinding, AUTO)


PB_BIND(zmk_analog_keymap_SetAnalogLayerBindingRequest, zmk_analog_keymap_SetAnalogLayerBindingRequest, AUTO)





