/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_ZMK_ANALOG_KEYMAP_ANALOG_KEYMAP_PB_H_INCLUDED
#define PB_ZMK_ANALOG_KEYMAP_ANALOG_KEYMAP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _zmk_analog_keymap_SetAnalogLayerBindingResponse {
    zmk_analog_keymap_SetAnalogLayerBindingResponse_SET_ANALOG_LAYER_BINDING_RESP_OK = 0,
    zmk_analog_keymap_SetAnalogLayerBindingResponse_SET_ANALOG_LAYER_BINDING_RESP_INVALID_LOCATION = 1,
    zmk_analog_keymap_SetAnalogLayerBindingResponse_SET_ANALOG_LAYER_BINDING_RESP_INVALID_BEHAVIOR = 2,
    zmk_analog_keymap_SetAnalogLayerBindingResponse_SET_ANALOG_LAYER_BINDING_RESP_INVALID_PARAMETERS = 3
} zmk_analog_keymap_SetAnalogLayerBindingResponse;

/* Struct definitions */
typedef struct _zmk_analog_keymap_AnalogKeymap {
    pb_callback_t layers;
    uint32_t available_layers;
    uint32_t max_layer_name_length;
} zmk_analog_keymap_AnalogKeymap;

typedef struct _zmk_analog_keymap_Response {
    pb_size_t which_response_type;
    union {
        zmk_analog_keymap_AnalogKeymap get_analog_keymap;
        zmk_analog_keymap_SetAnalogLayerBindingResponse set_analog_layer_binding;
    } response_type;
} zmk_analog_keymap_Response;

typedef struct _zmk_analog_keymap_AnalogLayer {
    uint32_t id;
    pb_callback_t name;
    pb_callback_t bindings;
} zmk_analog_keymap_AnalogLayer;

typedef struct _zmk_analog_keymap_AnalogBehaviorBinding {
    uint32_t analog_behavior_id;
    int32_t param0;
    int32_t param1;
    int32_t param2;
    int32_t param3;
} zmk_analog_keymap_AnalogBehaviorBinding;

typedef struct _zmk_analog_keymap_SetAnalogLayerBindingRequest {
    uint32_t analog_layer_id;
    int32_t key_position;
    bool has_analog_binding;
    zmk_analog_keymap_AnalogBehaviorBinding analog_binding;
} zmk_analog_keymap_SetAnalogLayerBindingRequest;

typedef struct _zmk_analog_keymap_Request {
    pb_size_t which_request_type;
    union {
        bool get_analog_keymap;
        zmk_analog_keymap_SetAnalogLayerBindingRequest set_analog_layer_binding;
    } request_type;
} zmk_analog_keymap_Request;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _zmk_analog_keymap_SetAnalogLayerBindingResponse_MIN zmk_analog_keymap_SetAnalogLayerBindingResponse_SET_ANALOG_LAYER_BINDING_RESP_OK
#define _zmk_analog_keymap_SetAnalogLayerBindingResponse_MAX zmk_analog_keymap_SetAnalogLayerBindingResponse_SET_ANALOG_LAYER_BINDING_RESP_INVALID_PARAMETERS
#define _zmk_analog_keymap_SetAnalogLayerBindingResponse_ARRAYSIZE ((zmk_analog_keymap_SetAnalogLayerBindingResponse)(zmk_analog_keymap_SetAnalogLayerBindingResponse_SET_ANALOG_LAYER_BINDING_RESP_INVALID_PARAMETERS+1))


#define zmk_analog_keymap_Response_response_type_set_analog_layer_binding_ENUMTYPE zmk_analog_keymap_SetAnalogLayerBindingResponse






/* Initializer values for message structs */
#define zmk_analog_keymap_Request_init_default   {0, {0}}
#define zmk_analog_keymap_Response_init_default  {0, {zmk_analog_keymap_AnalogKeymap_init_default}}
#define zmk_analog_keymap_AnalogKeymap_init_default {{{NULL}, NULL}, 0, 0}
#define zmk_analog_keymap_AnalogLayer_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define zmk_analog_keymap_AnalogBehaviorBinding_init_default {0, 0, 0, 0, 0}
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_init_default {0, 0, false, zmk_analog_keymap_AnalogBehaviorBinding_init_default}
#define zmk_analog_keymap_Request_init_zero      {0, {0}}
#define zmk_analog_keymap_Response_init_zero     {0, {zmk_analog_keymap_AnalogKeymap_init_zero}}
#define zmk_analog_keymap_AnalogKeymap_init_zero {{{NULL}, NULL}, 0, 0}
#define zmk_analog_keymap_AnalogLayer_init_zero  {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define zmk_analog_keymap_AnalogBehaviorBinding_init_zero {0, 0, 0, 0, 0}
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_init_zero {0, 0, false, zmk_analog_keymap_AnalogBehaviorBinding_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define zmk_analog_keymap_AnalogKeymap_layers_tag 1
#define zmk_analog_keymap_AnalogKeymap_available_layers_tag 2
#define zmk_analog_keymap_AnalogKeymap_max_layer_name_length_tag 3
#define zmk_analog_keymap_Response_get_analog_keymap_tag 1
#define zmk_analog_keymap_Response_set_analog_layer_binding_tag 64
#define zmk_analog_keymap_AnalogLayer_id_tag     1
#define zmk_analog_keymap_AnalogLayer_name_tag   2
#define zmk_analog_keymap_AnalogLayer_bindings_tag 3
#define zmk_analog_keymap_AnalogBehaviorBinding_analog_behavior_id_tag 1
#define zmk_analog_keymap_AnalogBehaviorBinding_param0_tag 2
#define zmk_analog_keymap_AnalogBehaviorBinding_param1_tag 3
#define zmk_analog_keymap_AnalogBehaviorBinding_param2_tag 4
#define zmk_analog_keymap_AnalogBehaviorBinding_param3_tag 5
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_analog_layer_id_tag 1
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_key_position_tag 2
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_analog_binding_tag 3
#define zmk_analog_keymap_Request_get_analog_keymap_tag 1
#define zmk_analog_keymap_Request_set_analog_layer_binding_tag 64

/* Struct field encoding specification for nanopb */
#define zmk_analog_keymap_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BOOL,     (request_type,get_analog_keymap,request_type.get_analog_keymap),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,set_analog_layer_binding,request_type.set_analog_layer_binding),  64)
#define zmk_analog_keymap_Request_CALLBACK NULL
#define zmk_analog_keymap_Request_DEFAULT NULL
#define zmk_analog_keymap_Request_request_type_set_analog_layer_binding_MSGTYPE zmk_analog_keymap_SetAnalogLayerBindingRequest

#define zmk_analog_keymap_Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,get_analog_keymap,response_type.get_analog_keymap),   1) \
X(a, STATIC,   ONEOF,    UENUM,    (response_type,set_analog_layer_binding,response_type.set_analog_layer_binding),  64)
#define zmk_analog_keymap_Response_CALLBACK NULL
#define zmk_analog_keymap_Response_DEFAULT NULL
#define zmk_analog_keymap_Response_response_type_get_analog_keymap_MSGTYPE zmk_analog_keymap_AnalogKeymap

#define zmk_analog_keymap_AnalogKeymap_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  layers,            1) \
X(a, STATIC,   SINGULAR, UINT32,   available_layers,   2) \
X(a, STATIC,   SINGULAR, UINT32,   max_layer_name_length,   3)
#define zmk_analog_keymap_AnalogKeymap_CALLBACK pb_default_field_callback
#define zmk_analog_keymap_AnalogKeymap_DEFAULT NULL
#define zmk_analog_keymap_AnalogKeymap_layers_MSGTYPE zmk_analog_keymap_AnalogLayer

#define zmk_analog_keymap_AnalogLayer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, REPEATED, MESSAGE,  bindings,          3)
#define zmk_analog_keymap_AnalogLayer_CALLBACK pb_default_field_callback
#define zmk_analog_keymap_AnalogLayer_DEFAULT NULL
#define zmk_analog_keymap_AnalogLayer_bindings_MSGTYPE zmk_analog_keymap_AnalogBehaviorBinding

#define zmk_analog_keymap_AnalogBehaviorBinding_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   analog_behavior_id,   1) \
X(a, STATIC,   SINGULAR, SINT32,   param0,            2) \
X(a, STATIC,   SINGULAR, SINT32,   param1,            3) \
X(a, STATIC,   SINGULAR, SINT32,   param2,            4) \
X(a, STATIC,   SINGULAR, SINT32,   param3,            5)
#define zmk_analog_keymap_AnalogBehaviorBinding_CALLBACK NULL
#define zmk_analog_keymap_AnalogBehaviorBinding_DEFAULT NULL

#define zmk_analog_keymap_SetAnalogLayerBindingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   analog_layer_id,   1) \
X(a, STATIC,   SINGULAR, INT32,    key_position,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  analog_binding,    3)
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_CALLBACK NULL
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_DEFAULT NULL
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_analog_binding_MSGTYPE zmk_analog_keymap_AnalogBehaviorBinding

extern const pb_msgdesc_t zmk_analog_keymap_Request_msg;
extern const pb_msgdesc_t zmk_analog_keymap_Response_msg;
extern const pb_msgdesc_t zmk_analog_keymap_AnalogKeymap_msg;
extern const pb_msgdesc_t zmk_analog_keymap_AnalogLayer_msg;
extern const pb_msgdesc_t zmk_analog_keymap_AnalogBehaviorBinding_msg;
extern const pb_msgdesc_t zmk_analog_keymap_SetAnalogLayerBindingRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define zmk_analog_keymap_Request_fields &zmk_analog_keymap_Request_msg
#define zmk_analog_keymap_Response_fields &zmk_analog_keymap_Response_msg
#define zmk_analog_keymap_AnalogKeymap_fields &zmk_analog_keymap_AnalogKeymap_msg
#define zmk_analog_keymap_AnalogLayer_fields &zmk_analog_keymap_AnalogLayer_msg
#define zmk_analog_keymap_AnalogBehaviorBinding_fields &zmk_analog_keymap_AnalogBehaviorBinding_msg
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_fields &zmk_analog_keymap_SetAnalogLayerBindingRequest_msg

/* Maximum encoded size of messages (where known) */
/* zmk_analog_keymap_Response_size depends on runtime parameters */
/* zmk_analog_keymap_AnalogKeymap_size depends on runtime parameters */
/* zmk_analog_keymap_AnalogLayer_size depends on runtime parameters */
#define ZMK_ANALOG_KEYMAP_ANALOG_KEYMAP_PB_H_MAX_SIZE zmk_analog_keymap_Request_size
#define zmk_analog_keymap_AnalogBehaviorBinding_size 30
#define zmk_analog_keymap_Request_size           52
#define zmk_analog_keymap_SetAnalogLayerBindingRequest_size 49

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
