/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "behaviors.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(zmk_behaviors_Request, zmk_behaviors_Request, 2)


PB_BIND(zmk_behaviors_GetBehaviorDetailsRequest, zmk_behaviors_GetBehaviorDetailsRequest, AUTO)


PB_BIND(zmk_behaviors_GetAnalogBehaviorDetailsRequest, zmk_behaviors_GetAnalogBehaviorDetailsRequest, AUTO)


PB_BIND(zmk_behaviors_Response, zmk_behaviors_Response, 2)


PB_BIND(zmk_behaviors_ListAllBehaviorsResponse, zmk_behaviors_ListAllBehaviorsResponse, 2)


PB_BIND(zmk_behaviors_GetBehaviorDetailsResponse, zmk_behaviors_GetBehaviorDetailsResponse, AUTO)


PB_BIND(zmk_behaviors_BehaviorBindingParametersSet, zmk_behaviors_BehaviorBindingParametersSet, AUTO)


PB_BIND(zmk_behaviors_BehaviorParameterValueDescriptionRange, zmk_behaviors_BehaviorParameterValueDescriptionRange, AUTO)


PB_BIND(zmk_behaviors_BehaviorParameterNil, zmk_behaviors_BehaviorParameterNil, AUTO)


PB_BIND(zmk_behaviors_BehaviorParameterLayerId, zmk_behaviors_BehaviorParameterLayerId, AUTO)


PB_BIND(zmk_behaviors_BehaviorParameterHidUsage, zmk_behaviors_BehaviorParameterHidUsage, AUTO)


PB_BIND(zmk_behaviors_BehaviorParameterValueDescription, zmk_behaviors_BehaviorParameterValueDescription, AUTO)


PB_BIND(zmk_behaviors_GetAnalogBehaviorDetailsResponse, zmk_behaviors_GetAnalogBehaviorDetailsResponse, AUTO)


PB_BIND(zmk_behaviors_AnalogBehaviorBindingParametersSet, zmk_behaviors_AnalogBehaviorBindingParametersSet, AUTO)


PB_BIND(zmk_behaviors_AnalogBehaviorParameterValueCalibratedRange, zmk_behaviors_AnalogBehaviorParameterValueCalibratedRange, AUTO)


PB_BIND(zmk_behaviors_AnalogBehaviorParameterNil, zmk_behaviors_AnalogBehaviorParameterNil, AUTO)


PB_BIND(zmk_behaviors_AnalogBehaviorParameterValueDescription, zmk_behaviors_AnalogBehaviorParameterValueDescription, AUTO)



