/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_ZMK_LED_SETTINGS_LED_SETTINGS_PB_H_INCLUDED
#define PB_ZMK_LED_SETTINGS_LED_SETTINGS_PB_H_INCLUDED
#include <pb.h>
#include "values_wrappers.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _zmk_led_settings_LedSettingChangeBool {
    zmk_led_settings_LedSettingChangeBool_TGL = 0,
    zmk_led_settings_LedSettingChangeBool_SET = 1,
    zmk_led_settings_LedSettingChangeBool_CLR = 2
} zmk_led_settings_LedSettingChangeBool;

typedef enum _zmk_led_settings_ChangeTypeInt {
    zmk_led_settings_ChangeTypeInt_SET_VALUE = 0,
    zmk_led_settings_ChangeTypeInt_ADD_VALUE = 1
} zmk_led_settings_ChangeTypeInt;

typedef enum _zmk_led_settings_LedSettingsErrorCode {
    zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_OK = 0,
    zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_GENERIC = 1,
    zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_INVALID_VALUE = 2,
    zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_INVALID_CHANGE_TYPE = 3,
    zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_INVALID_DEVICE = 4,
    zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_TOO_MANY_CHANGES = 5,
    zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_INVALID_SETTINGS = 6
} zmk_led_settings_LedSettingsErrorCode;

/* Struct definitions */
typedef struct _zmk_led_settings_LedSettingsSetRequest {
    pb_size_t which_target;
    union {
        uint32_t settings_id;
        uint32_t effect_id;
    } target;
    pb_callback_t values;
} zmk_led_settings_LedSettingsSetRequest;

typedef struct _zmk_led_settings_LedSettingsGetRequest {
    pb_size_t which_info;
    union {
        uint32_t settings;
        uint32_t effects;
    } info;
} zmk_led_settings_LedSettingsGetRequest;

typedef struct _zmk_led_settings_LedSettingsGetValuesRequest {
    pb_size_t which_target;
    union {
        uint32_t settings_id;
        uint32_t effect_id;
    } target;
} zmk_led_settings_LedSettingsGetValuesRequest;

typedef struct _zmk_led_settings_Request {
    pb_size_t which_request_type;
    union {
        zmk_led_settings_LedSettingsSetRequest led_settings_set;
        zmk_led_settings_LedSettingsGetRequest led_settings_get_info;
        zmk_led_settings_LedSettingsGetValuesRequest led_settings_get_values;
    } request_type;
} zmk_led_settings_Request;

typedef struct _zmk_led_settings_LedSettingChangeInt {
    zmk_led_settings_ChangeTypeInt change_type;
    int32_t value;
} zmk_led_settings_LedSettingChangeInt;

typedef struct _zmk_led_settings_Values {
    pb_size_t which_item;
    union {
        zmk_led_settings_LedSettingChangeInt hue;
        zmk_led_settings_LedSettingChangeInt saturation;
        zmk_led_settings_LedSettingChangeInt brightness;
        zmk_led_settings_LedSettingChangeInt speed_factor;
        zmk_led_settings_LedSettingChangeInt selected_effect;
        zmk_led_settings_LedSettingChangeBool enabled;
    } item;
} zmk_led_settings_Values;

typedef struct _zmk_led_settings_LedSettingsSetResponse {
    zmk_led_settings_LedSettingsErrorCode err;
} zmk_led_settings_LedSettingsSetResponse;

typedef struct _zmk_led_settings_LedSettingsNodesInfo {
    pb_callback_t data;
} zmk_led_settings_LedSettingsNodesInfo;

typedef struct _zmk_led_settings_LedEffectsNodesInfo {
    pb_callback_t data;
} zmk_led_settings_LedEffectsNodesInfo;

typedef struct _zmk_led_settings_LedSettingsGetResponse {
    pb_size_t which_result;
    union {
        zmk_led_settings_LedSettingsErrorCode err;
        zmk_led_settings_LedSettingsNodesInfo settings_data;
        zmk_led_settings_LedEffectsNodesInfo effects_data;
    } result;
} zmk_led_settings_LedSettingsGetResponse;

typedef struct _zmk_led_settings_LedSettingsNodeInfo {
    uint32_t studio_id;
    /* field corresponds to the BIT values
 actually this BITs field values shows which params can be changed
 BIT(27) -> LED_EFFECT_SETTINGS_FLAG_SPD_1_STORE -      speed change
 BIT(28) -> LED_EFFECT_SETTINGS_STORE_FLAG_HUE_1 -      hue change
 BIT(29) -> LED_EFFECT_SETTINGS_STORE_FLAG_SAT_1 -      saturation change
 BIT(30) -> LED_EFFECT_SETTINGS_STORE_FLAG_BRI_1 -      brightness change
 BIT(31) -> LED_EFFECT_SETTINGS_STORE_FLAG_SEL_EFFECT - selected effect change */
    uint32_t storage_flags;
    bool has_parent_studio_id;
    UInt32Value parent_studio_id;
} zmk_led_settings_LedSettingsNodeInfo;

typedef struct _zmk_led_settings_LedEffectNodeInfo {
    pb_callback_t effect_name;
    uint32_t studio_id;
    bool has_parent_studio_id;
    UInt32Value parent_studio_id;
    uint32_t settings_studio_id;
} zmk_led_settings_LedEffectNodeInfo;

typedef struct _zmk_led_settings_LedSettingsValues {
    bool has_hue_1_stored;
    UInt32Value hue_1_stored;
    bool has_hue_1_effective;
    UInt32Value hue_1_effective;
    bool has_brightness_1_stored;
    UInt32Value brightness_1_stored;
    bool has_brightness_1_effective;
    UInt32Value brightness_1_effective;
    bool has_saturation_1_stored;
    UInt32Value saturation_1_stored;
    bool has_saturation_1_effective;
    UInt32Value saturation_1_effective;
    bool has_speed_factor_stored;
    UInt32Value speed_factor_stored;
    bool has_speed_factor_effective;
    UInt32Value speed_factor_effective;
    bool has_selected_effect_stored;
    UInt32Value selected_effect_stored;
    bool has_enabled_stored;
    UInt32Value enabled_stored;
} zmk_led_settings_LedSettingsValues;

typedef struct _zmk_led_settings_LedSettingsGetValuesResponse {
    pb_size_t which_result;
    union {
        zmk_led_settings_LedSettingsErrorCode err;
        zmk_led_settings_LedSettingsValues values;
    } result;
} zmk_led_settings_LedSettingsGetValuesResponse;

typedef struct _zmk_led_settings_Response {
    pb_size_t which_response_type;
    union {
        zmk_led_settings_LedSettingsSetResponse led_settings_set;
        zmk_led_settings_LedSettingsGetResponse led_settings_get_info;
        zmk_led_settings_LedSettingsGetValuesResponse led_settings_get_values;
    } response_type;
} zmk_led_settings_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _zmk_led_settings_LedSettingChangeBool_MIN zmk_led_settings_LedSettingChangeBool_TGL
#define _zmk_led_settings_LedSettingChangeBool_MAX zmk_led_settings_LedSettingChangeBool_CLR
#define _zmk_led_settings_LedSettingChangeBool_ARRAYSIZE ((zmk_led_settings_LedSettingChangeBool)(zmk_led_settings_LedSettingChangeBool_CLR+1))

#define _zmk_led_settings_ChangeTypeInt_MIN zmk_led_settings_ChangeTypeInt_SET_VALUE
#define _zmk_led_settings_ChangeTypeInt_MAX zmk_led_settings_ChangeTypeInt_ADD_VALUE
#define _zmk_led_settings_ChangeTypeInt_ARRAYSIZE ((zmk_led_settings_ChangeTypeInt)(zmk_led_settings_ChangeTypeInt_ADD_VALUE+1))

#define _zmk_led_settings_LedSettingsErrorCode_MIN zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_OK
#define _zmk_led_settings_LedSettingsErrorCode_MAX zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_INVALID_SETTINGS
#define _zmk_led_settings_LedSettingsErrorCode_ARRAYSIZE ((zmk_led_settings_LedSettingsErrorCode)(zmk_led_settings_LedSettingsErrorCode_LED_SETTINGS_ERR_INVALID_SETTINGS+1))






#define zmk_led_settings_Values_item_enabled_ENUMTYPE zmk_led_settings_LedSettingChangeBool

#define zmk_led_settings_LedSettingChangeInt_change_type_ENUMTYPE zmk_led_settings_ChangeTypeInt

#define zmk_led_settings_LedSettingsSetResponse_err_ENUMTYPE zmk_led_settings_LedSettingsErrorCode

#define zmk_led_settings_LedSettingsGetResponse_result_err_ENUMTYPE zmk_led_settings_LedSettingsErrorCode

#define zmk_led_settings_LedSettingsGetValuesResponse_result_err_ENUMTYPE zmk_led_settings_LedSettingsErrorCode







/* Initializer values for message structs */
#define zmk_led_settings_Request_init_default    {0, {zmk_led_settings_LedSettingsSetRequest_init_default}}
#define zmk_led_settings_Response_init_default   {0, {zmk_led_settings_LedSettingsSetResponse_init_default}}
#define zmk_led_settings_LedSettingsSetRequest_init_default {0, {0}, {{NULL}, NULL}}
#define zmk_led_settings_LedSettingsGetRequest_init_default {0, {0}}
#define zmk_led_settings_LedSettingsGetValuesRequest_init_default {0, {0}}
#define zmk_led_settings_Values_init_default     {0, {zmk_led_settings_LedSettingChangeInt_init_default}}
#define zmk_led_settings_LedSettingChangeInt_init_default {_zmk_led_settings_ChangeTypeInt_MIN, 0}
#define zmk_led_settings_LedSettingsSetResponse_init_default {_zmk_led_settings_LedSettingsErrorCode_MIN}
#define zmk_led_settings_LedSettingsGetResponse_init_default {0, {_zmk_led_settings_LedSettingsErrorCode_MIN}}
#define zmk_led_settings_LedSettingsGetValuesResponse_init_default {0, {_zmk_led_settings_LedSettingsErrorCode_MIN}}
#define zmk_led_settings_LedSettingsNodesInfo_init_default {{{NULL}, NULL}}
#define zmk_led_settings_LedEffectsNodesInfo_init_default {{{NULL}, NULL}}
#define zmk_led_settings_LedSettingsNodeInfo_init_default {0, 0, false, UInt32Value_init_default}
#define zmk_led_settings_LedEffectNodeInfo_init_default {{{NULL}, NULL}, 0, false, UInt32Value_init_default, 0}
#define zmk_led_settings_LedSettingsValues_init_default {false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default, false, UInt32Value_init_default}
#define zmk_led_settings_Request_init_zero       {0, {zmk_led_settings_LedSettingsSetRequest_init_zero}}
#define zmk_led_settings_Response_init_zero      {0, {zmk_led_settings_LedSettingsSetResponse_init_zero}}
#define zmk_led_settings_LedSettingsSetRequest_init_zero {0, {0}, {{NULL}, NULL}}
#define zmk_led_settings_LedSettingsGetRequest_init_zero {0, {0}}
#define zmk_led_settings_LedSettingsGetValuesRequest_init_zero {0, {0}}
#define zmk_led_settings_Values_init_zero        {0, {zmk_led_settings_LedSettingChangeInt_init_zero}}
#define zmk_led_settings_LedSettingChangeInt_init_zero {_zmk_led_settings_ChangeTypeInt_MIN, 0}
#define zmk_led_settings_LedSettingsSetResponse_init_zero {_zmk_led_settings_LedSettingsErrorCode_MIN}
#define zmk_led_settings_LedSettingsGetResponse_init_zero {0, {_zmk_led_settings_LedSettingsErrorCode_MIN}}
#define zmk_led_settings_LedSettingsGetValuesResponse_init_zero {0, {_zmk_led_settings_LedSettingsErrorCode_MIN}}
#define zmk_led_settings_LedSettingsNodesInfo_init_zero {{{NULL}, NULL}}
#define zmk_led_settings_LedEffectsNodesInfo_init_zero {{{NULL}, NULL}}
#define zmk_led_settings_LedSettingsNodeInfo_init_zero {0, 0, false, UInt32Value_init_zero}
#define zmk_led_settings_LedEffectNodeInfo_init_zero {{{NULL}, NULL}, 0, false, UInt32Value_init_zero, 0}
#define zmk_led_settings_LedSettingsValues_init_zero {false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero, false, UInt32Value_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define zmk_led_settings_LedSettingsSetRequest_settings_id_tag 1
#define zmk_led_settings_LedSettingsSetRequest_effect_id_tag 2
#define zmk_led_settings_LedSettingsSetRequest_values_tag 3
#define zmk_led_settings_LedSettingsGetRequest_settings_tag 1
#define zmk_led_settings_LedSettingsGetRequest_effects_tag 2
#define zmk_led_settings_LedSettingsGetValuesRequest_settings_id_tag 1
#define zmk_led_settings_LedSettingsGetValuesRequest_effect_id_tag 2
#define zmk_led_settings_Request_led_settings_set_tag 1
#define zmk_led_settings_Request_led_settings_get_info_tag 2
#define zmk_led_settings_Request_led_settings_get_values_tag 3
#define zmk_led_settings_LedSettingChangeInt_change_type_tag 1
#define zmk_led_settings_LedSettingChangeInt_value_tag 2
#define zmk_led_settings_Values_hue_tag          4
#define zmk_led_settings_Values_saturation_tag   5
#define zmk_led_settings_Values_brightness_tag   6
#define zmk_led_settings_Values_speed_factor_tag 7
#define zmk_led_settings_Values_selected_effect_tag 8
#define zmk_led_settings_Values_enabled_tag      9
#define zmk_led_settings_LedSettingsSetResponse_err_tag 1
#define zmk_led_settings_LedSettingsNodesInfo_data_tag 1
#define zmk_led_settings_LedEffectsNodesInfo_data_tag 1
#define zmk_led_settings_LedSettingsGetResponse_err_tag 1
#define zmk_led_settings_LedSettingsGetResponse_settings_data_tag 2
#define zmk_led_settings_LedSettingsGetResponse_effects_data_tag 3
#define zmk_led_settings_LedSettingsNodeInfo_studio_id_tag 1
#define zmk_led_settings_LedSettingsNodeInfo_storage_flags_tag 2
#define zmk_led_settings_LedSettingsNodeInfo_parent_studio_id_tag 3
#define zmk_led_settings_LedEffectNodeInfo_effect_name_tag 1
#define zmk_led_settings_LedEffectNodeInfo_studio_id_tag 2
#define zmk_led_settings_LedEffectNodeInfo_parent_studio_id_tag 3
#define zmk_led_settings_LedEffectNodeInfo_settings_studio_id_tag 4
#define zmk_led_settings_LedSettingsValues_hue_1_stored_tag 1
#define zmk_led_settings_LedSettingsValues_hue_1_effective_tag 2
#define zmk_led_settings_LedSettingsValues_brightness_1_stored_tag 3
#define zmk_led_settings_LedSettingsValues_brightness_1_effective_tag 4
#define zmk_led_settings_LedSettingsValues_saturation_1_stored_tag 5
#define zmk_led_settings_LedSettingsValues_saturation_1_effective_tag 6
#define zmk_led_settings_LedSettingsValues_speed_factor_stored_tag 7
#define zmk_led_settings_LedSettingsValues_speed_factor_effective_tag 8
#define zmk_led_settings_LedSettingsValues_selected_effect_stored_tag 9
#define zmk_led_settings_LedSettingsValues_enabled_stored_tag 10
#define zmk_led_settings_LedSettingsGetValuesResponse_err_tag 1
#define zmk_led_settings_LedSettingsGetValuesResponse_values_tag 2
#define zmk_led_settings_Response_led_settings_set_tag 1
#define zmk_led_settings_Response_led_settings_get_info_tag 2
#define zmk_led_settings_Response_led_settings_get_values_tag 3

/* Struct field encoding specification for nanopb */
#define zmk_led_settings_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,led_settings_set,request_type.led_settings_set),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,led_settings_get_info,request_type.led_settings_get_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,led_settings_get_values,request_type.led_settings_get_values),   3)
#define zmk_led_settings_Request_CALLBACK NULL
#define zmk_led_settings_Request_DEFAULT NULL
#define zmk_led_settings_Request_request_type_led_settings_set_MSGTYPE zmk_led_settings_LedSettingsSetRequest
#define zmk_led_settings_Request_request_type_led_settings_get_info_MSGTYPE zmk_led_settings_LedSettingsGetRequest
#define zmk_led_settings_Request_request_type_led_settings_get_values_MSGTYPE zmk_led_settings_LedSettingsGetValuesRequest

#define zmk_led_settings_Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,led_settings_set,response_type.led_settings_set),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,led_settings_get_info,response_type.led_settings_get_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,led_settings_get_values,response_type.led_settings_get_values),   3)
#define zmk_led_settings_Response_CALLBACK NULL
#define zmk_led_settings_Response_DEFAULT NULL
#define zmk_led_settings_Response_response_type_led_settings_set_MSGTYPE zmk_led_settings_LedSettingsSetResponse
#define zmk_led_settings_Response_response_type_led_settings_get_info_MSGTYPE zmk_led_settings_LedSettingsGetResponse
#define zmk_led_settings_Response_response_type_led_settings_get_values_MSGTYPE zmk_led_settings_LedSettingsGetValuesResponse

#define zmk_led_settings_LedSettingsSetRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (target,settings_id,target.settings_id),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (target,effect_id,target.effect_id),   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            3)
#define zmk_led_settings_LedSettingsSetRequest_CALLBACK pb_default_field_callback
#define zmk_led_settings_LedSettingsSetRequest_DEFAULT NULL
#define zmk_led_settings_LedSettingsSetRequest_values_MSGTYPE zmk_led_settings_Values

#define zmk_led_settings_LedSettingsGetRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (info,settings,info.settings),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (info,effects,info.effects),   2)
#define zmk_led_settings_LedSettingsGetRequest_CALLBACK NULL
#define zmk_led_settings_LedSettingsGetRequest_DEFAULT NULL

#define zmk_led_settings_LedSettingsGetValuesRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (target,settings_id,target.settings_id),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (target,effect_id,target.effect_id),   2)
#define zmk_led_settings_LedSettingsGetValuesRequest_CALLBACK NULL
#define zmk_led_settings_LedSettingsGetValuesRequest_DEFAULT NULL

#define zmk_led_settings_Values_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (item,hue,item.hue),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (item,saturation,item.saturation),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (item,brightness,item.brightness),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (item,speed_factor,item.speed_factor),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (item,selected_effect,item.selected_effect),   8) \
X(a, STATIC,   ONEOF,    UENUM,    (item,enabled,item.enabled),   9)
#define zmk_led_settings_Values_CALLBACK NULL
#define zmk_led_settings_Values_DEFAULT NULL
#define zmk_led_settings_Values_item_hue_MSGTYPE zmk_led_settings_LedSettingChangeInt
#define zmk_led_settings_Values_item_saturation_MSGTYPE zmk_led_settings_LedSettingChangeInt
#define zmk_led_settings_Values_item_brightness_MSGTYPE zmk_led_settings_LedSettingChangeInt
#define zmk_led_settings_Values_item_speed_factor_MSGTYPE zmk_led_settings_LedSettingChangeInt
#define zmk_led_settings_Values_item_selected_effect_MSGTYPE zmk_led_settings_LedSettingChangeInt

#define zmk_led_settings_LedSettingChangeInt_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    change_type,       1) \
X(a, STATIC,   SINGULAR, SINT32,   value,             2)
#define zmk_led_settings_LedSettingChangeInt_CALLBACK NULL
#define zmk_led_settings_LedSettingChangeInt_DEFAULT NULL

#define zmk_led_settings_LedSettingsSetResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    err,               1)
#define zmk_led_settings_LedSettingsSetResponse_CALLBACK NULL
#define zmk_led_settings_LedSettingsSetResponse_DEFAULT NULL

#define zmk_led_settings_LedSettingsGetResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (result,err,result.err),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,settings_data,result.settings_data),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,effects_data,result.effects_data),   3)
#define zmk_led_settings_LedSettingsGetResponse_CALLBACK NULL
#define zmk_led_settings_LedSettingsGetResponse_DEFAULT NULL
#define zmk_led_settings_LedSettingsGetResponse_result_settings_data_MSGTYPE zmk_led_settings_LedSettingsNodesInfo
#define zmk_led_settings_LedSettingsGetResponse_result_effects_data_MSGTYPE zmk_led_settings_LedEffectsNodesInfo

#define zmk_led_settings_LedSettingsGetValuesResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (result,err,result.err),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,values,result.values),   2)
#define zmk_led_settings_LedSettingsGetValuesResponse_CALLBACK NULL
#define zmk_led_settings_LedSettingsGetValuesResponse_DEFAULT NULL
#define zmk_led_settings_LedSettingsGetValuesResponse_result_values_MSGTYPE zmk_led_settings_LedSettingsValues

#define zmk_led_settings_LedSettingsNodesInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  data,              1)
#define zmk_led_settings_LedSettingsNodesInfo_CALLBACK pb_default_field_callback
#define zmk_led_settings_LedSettingsNodesInfo_DEFAULT NULL
#define zmk_led_settings_LedSettingsNodesInfo_data_MSGTYPE zmk_led_settings_LedSettingsNodeInfo

#define zmk_led_settings_LedEffectsNodesInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  data,              1)
#define zmk_led_settings_LedEffectsNodesInfo_CALLBACK pb_default_field_callback
#define zmk_led_settings_LedEffectsNodesInfo_DEFAULT NULL
#define zmk_led_settings_LedEffectsNodesInfo_data_MSGTYPE zmk_led_settings_LedEffectNodeInfo

#define zmk_led_settings_LedSettingsNodeInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   studio_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   storage_flags,     2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parent_studio_id,   3)
#define zmk_led_settings_LedSettingsNodeInfo_CALLBACK NULL
#define zmk_led_settings_LedSettingsNodeInfo_DEFAULT NULL
#define zmk_led_settings_LedSettingsNodeInfo_parent_studio_id_MSGTYPE UInt32Value

#define zmk_led_settings_LedEffectNodeInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   effect_name,       1) \
X(a, STATIC,   SINGULAR, UINT32,   studio_id,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parent_studio_id,   3) \
X(a, STATIC,   SINGULAR, UINT32,   settings_studio_id,   4)
#define zmk_led_settings_LedEffectNodeInfo_CALLBACK pb_default_field_callback
#define zmk_led_settings_LedEffectNodeInfo_DEFAULT NULL
#define zmk_led_settings_LedEffectNodeInfo_parent_studio_id_MSGTYPE UInt32Value

#define zmk_led_settings_LedSettingsValues_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hue_1_stored,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hue_1_effective,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  brightness_1_stored,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  brightness_1_effective,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  saturation_1_stored,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  saturation_1_effective,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  speed_factor_stored,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  speed_factor_effective,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  selected_effect_stored,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enabled_stored,   10)
#define zmk_led_settings_LedSettingsValues_CALLBACK NULL
#define zmk_led_settings_LedSettingsValues_DEFAULT NULL
#define zmk_led_settings_LedSettingsValues_hue_1_stored_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_hue_1_effective_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_brightness_1_stored_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_brightness_1_effective_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_saturation_1_stored_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_saturation_1_effective_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_speed_factor_stored_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_speed_factor_effective_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_selected_effect_stored_MSGTYPE UInt32Value
#define zmk_led_settings_LedSettingsValues_enabled_stored_MSGTYPE UInt32Value

extern const pb_msgdesc_t zmk_led_settings_Request_msg;
extern const pb_msgdesc_t zmk_led_settings_Response_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsSetRequest_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsGetRequest_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsGetValuesRequest_msg;
extern const pb_msgdesc_t zmk_led_settings_Values_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingChangeInt_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsSetResponse_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsGetResponse_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsGetValuesResponse_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsNodesInfo_msg;
extern const pb_msgdesc_t zmk_led_settings_LedEffectsNodesInfo_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsNodeInfo_msg;
extern const pb_msgdesc_t zmk_led_settings_LedEffectNodeInfo_msg;
extern const pb_msgdesc_t zmk_led_settings_LedSettingsValues_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define zmk_led_settings_Request_fields &zmk_led_settings_Request_msg
#define zmk_led_settings_Response_fields &zmk_led_settings_Response_msg
#define zmk_led_settings_LedSettingsSetRequest_fields &zmk_led_settings_LedSettingsSetRequest_msg
#define zmk_led_settings_LedSettingsGetRequest_fields &zmk_led_settings_LedSettingsGetRequest_msg
#define zmk_led_settings_LedSettingsGetValuesRequest_fields &zmk_led_settings_LedSettingsGetValuesRequest_msg
#define zmk_led_settings_Values_fields &zmk_led_settings_Values_msg
#define zmk_led_settings_LedSettingChangeInt_fields &zmk_led_settings_LedSettingChangeInt_msg
#define zmk_led_settings_LedSettingsSetResponse_fields &zmk_led_settings_LedSettingsSetResponse_msg
#define zmk_led_settings_LedSettingsGetResponse_fields &zmk_led_settings_LedSettingsGetResponse_msg
#define zmk_led_settings_LedSettingsGetValuesResponse_fields &zmk_led_settings_LedSettingsGetValuesResponse_msg
#define zmk_led_settings_LedSettingsNodesInfo_fields &zmk_led_settings_LedSettingsNodesInfo_msg
#define zmk_led_settings_LedEffectsNodesInfo_fields &zmk_led_settings_LedEffectsNodesInfo_msg
#define zmk_led_settings_LedSettingsNodeInfo_fields &zmk_led_settings_LedSettingsNodeInfo_msg
#define zmk_led_settings_LedEffectNodeInfo_fields &zmk_led_settings_LedEffectNodeInfo_msg
#define zmk_led_settings_LedSettingsValues_fields &zmk_led_settings_LedSettingsValues_msg

/* Maximum encoded size of messages (where known) */
/* zmk_led_settings_Request_size depends on runtime parameters */
/* zmk_led_settings_Response_size depends on runtime parameters */
/* zmk_led_settings_LedSettingsSetRequest_size depends on runtime parameters */
/* zmk_led_settings_LedSettingsGetResponse_size depends on runtime parameters */
/* zmk_led_settings_LedSettingsNodesInfo_size depends on runtime parameters */
/* zmk_led_settings_LedEffectsNodesInfo_size depends on runtime parameters */
/* zmk_led_settings_LedEffectNodeInfo_size depends on runtime parameters */
#define ZMK_LED_SETTINGS_LED_SETTINGS_PB_H_MAX_SIZE zmk_led_settings_LedSettingsGetValuesResponse_size
#define zmk_led_settings_LedSettingChangeInt_size 8
#define zmk_led_settings_LedSettingsGetRequest_size 6
#define zmk_led_settings_LedSettingsGetValuesRequest_size 6
#define zmk_led_settings_LedSettingsGetValuesResponse_size 82
#define zmk_led_settings_LedSettingsNodeInfo_size 20
#define zmk_led_settings_LedSettingsSetResponse_size 2
#define zmk_led_settings_LedSettingsValues_size  80
#define zmk_led_settings_Values_size             10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
