/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "testing.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(zmk_testing_Request, zmk_testing_Request, AUTO)


PB_BIND(zmk_testing_Response, zmk_testing_Response, AUTO)


PB_BIND(zmk_testing_ExecuteProgramRequest, zmk_testing_ExecuteProgramRequest, AUTO)









