/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_ZMK_TESTING_TESTING_PB_H_INCLUDED
#define PB_ZMK_TESTING_TESTING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _zmk_testing_ExecuteProgramApi {
    zmk_testing_ExecuteProgramApi_EXECUTE_PROGRAM_API_TEST_FULL = 0
} zmk_testing_ExecuteProgramApi;

typedef enum _zmk_testing_ExecuteProgramEndian {
    zmk_testing_ExecuteProgramEndian_EXECUTE_PROGRAM_ENDIAN_LITTLE = 0 /* big Endian is not yet implemented */
} zmk_testing_ExecuteProgramEndian;

typedef enum _zmk_testing_ExecuteProgramResponse {
    zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_OK = 0,
    zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_ERR_GENERIC = 1,
    zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_ERR_MEMORY = 2,
    zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_ERR_ENDIAN = 3,
    zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_ERR_API = 4
} zmk_testing_ExecuteProgramResponse;

/* Struct definitions */
typedef struct _zmk_testing_Response {
    pb_size_t which_response_type;
    union {
        zmk_testing_ExecuteProgramResponse execute_program;
    } response_type;
} zmk_testing_Response;

typedef struct _zmk_testing_ExecuteProgramRequest {
    /* Target Machine index (currently always 0) */
    uint32_t index;
    /* Target Machine index (currently always 0) */
    zmk_testing_ExecuteProgramApi api;
    /* Target Endian */
    zmk_testing_ExecuteProgramEndian endian;
    /* Size of global memory (including uninitialized data) */
    uint32_t global_size;
    /* minimal required stack size (use 0 if unknown) */
    uint32_t min_stack_size;
    /* instruction data */
    pb_callback_t instructions;
    /* global memory initializing data */
    pb_callback_t global_init;
} zmk_testing_ExecuteProgramRequest;

typedef struct _zmk_testing_Request {
    pb_size_t which_request_type;
    union {
        zmk_testing_ExecuteProgramRequest execute_program;
    } request_type;
} zmk_testing_Request;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _zmk_testing_ExecuteProgramApi_MIN zmk_testing_ExecuteProgramApi_EXECUTE_PROGRAM_API_TEST_FULL
#define _zmk_testing_ExecuteProgramApi_MAX zmk_testing_ExecuteProgramApi_EXECUTE_PROGRAM_API_TEST_FULL
#define _zmk_testing_ExecuteProgramApi_ARRAYSIZE ((zmk_testing_ExecuteProgramApi)(zmk_testing_ExecuteProgramApi_EXECUTE_PROGRAM_API_TEST_FULL+1))

#define _zmk_testing_ExecuteProgramEndian_MIN zmk_testing_ExecuteProgramEndian_EXECUTE_PROGRAM_ENDIAN_LITTLE
#define _zmk_testing_ExecuteProgramEndian_MAX zmk_testing_ExecuteProgramEndian_EXECUTE_PROGRAM_ENDIAN_LITTLE
#define _zmk_testing_ExecuteProgramEndian_ARRAYSIZE ((zmk_testing_ExecuteProgramEndian)(zmk_testing_ExecuteProgramEndian_EXECUTE_PROGRAM_ENDIAN_LITTLE+1))

#define _zmk_testing_ExecuteProgramResponse_MIN zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_OK
#define _zmk_testing_ExecuteProgramResponse_MAX zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_ERR_API
#define _zmk_testing_ExecuteProgramResponse_ARRAYSIZE ((zmk_testing_ExecuteProgramResponse)(zmk_testing_ExecuteProgramResponse_EXECUTE_PROGRAM_ERR_API+1))


#define zmk_testing_Response_response_type_execute_program_ENUMTYPE zmk_testing_ExecuteProgramResponse

#define zmk_testing_ExecuteProgramRequest_api_ENUMTYPE zmk_testing_ExecuteProgramApi
#define zmk_testing_ExecuteProgramRequest_endian_ENUMTYPE zmk_testing_ExecuteProgramEndian


/* Initializer values for message structs */
#define zmk_testing_Request_init_default         {0, {zmk_testing_ExecuteProgramRequest_init_default}}
#define zmk_testing_Response_init_default        {0, {_zmk_testing_ExecuteProgramResponse_MIN}}
#define zmk_testing_ExecuteProgramRequest_init_default {0, _zmk_testing_ExecuteProgramApi_MIN, _zmk_testing_ExecuteProgramEndian_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define zmk_testing_Request_init_zero            {0, {zmk_testing_ExecuteProgramRequest_init_zero}}
#define zmk_testing_Response_init_zero           {0, {_zmk_testing_ExecuteProgramResponse_MIN}}
#define zmk_testing_ExecuteProgramRequest_init_zero {0, _zmk_testing_ExecuteProgramApi_MIN, _zmk_testing_ExecuteProgramEndian_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define zmk_testing_Response_execute_program_tag 1
#define zmk_testing_ExecuteProgramRequest_index_tag 1
#define zmk_testing_ExecuteProgramRequest_api_tag 2
#define zmk_testing_ExecuteProgramRequest_endian_tag 3
#define zmk_testing_ExecuteProgramRequest_global_size_tag 4
#define zmk_testing_ExecuteProgramRequest_min_stack_size_tag 5
#define zmk_testing_ExecuteProgramRequest_instructions_tag 6
#define zmk_testing_ExecuteProgramRequest_global_init_tag 7
#define zmk_testing_Request_execute_program_tag  1

/* Struct field encoding specification for nanopb */
#define zmk_testing_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,execute_program,request_type.execute_program),   1)
#define zmk_testing_Request_CALLBACK NULL
#define zmk_testing_Request_DEFAULT NULL
#define zmk_testing_Request_request_type_execute_program_MSGTYPE zmk_testing_ExecuteProgramRequest

#define zmk_testing_Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (response_type,execute_program,response_type.execute_program),   1)
#define zmk_testing_Response_CALLBACK NULL
#define zmk_testing_Response_DEFAULT NULL

#define zmk_testing_ExecuteProgramRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, UENUM,    api,               2) \
X(a, STATIC,   SINGULAR, UENUM,    endian,            3) \
X(a, STATIC,   SINGULAR, UINT32,   global_size,       4) \
X(a, STATIC,   SINGULAR, UINT32,   min_stack_size,    5) \
X(a, CALLBACK, SINGULAR, BYTES,    instructions,      6) \
X(a, CALLBACK, SINGULAR, BYTES,    global_init,       7)
#define zmk_testing_ExecuteProgramRequest_CALLBACK pb_default_field_callback
#define zmk_testing_ExecuteProgramRequest_DEFAULT NULL

extern const pb_msgdesc_t zmk_testing_Request_msg;
extern const pb_msgdesc_t zmk_testing_Response_msg;
extern const pb_msgdesc_t zmk_testing_ExecuteProgramRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define zmk_testing_Request_fields &zmk_testing_Request_msg
#define zmk_testing_Response_fields &zmk_testing_Response_msg
#define zmk_testing_ExecuteProgramRequest_fields &zmk_testing_ExecuteProgramRequest_msg

/* Maximum encoded size of messages (where known) */
/* zmk_testing_Request_size depends on runtime parameters */
/* zmk_testing_ExecuteProgramRequest_size depends on runtime parameters */
#define ZMK_TESTING_TESTING_PB_H_MAX_SIZE        zmk_testing_Response_size
#define zmk_testing_Response_size                2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
