/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_VALUES_WRAPPERS_PB_H_INCLUDED
#define PB_VALUES_WRAPPERS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Wrapper message for `uint32`
 Take a primitive type and wraps it in a message
 This way submessage fields have presence */
typedef struct _UInt32Value {
    uint32_t value;
} UInt32Value;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define UInt32Value_init_default                 {0}
#define UInt32Value_init_zero                    {0}

/* Field tags (for use in manual encoding/decoding) */
#define UInt32Value_value_tag                    1

/* Struct field encoding specification for nanopb */
#define UInt32Value_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define UInt32Value_CALLBACK NULL
#define UInt32Value_DEFAULT NULL

extern const pb_msgdesc_t UInt32Value_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UInt32Value_fields &UInt32Value_msg

/* Maximum encoded size of messages (where known) */
#define UInt32Value_size                         6
#define VALUES_WRAPPERS_PB_H_MAX_SIZE            UInt32Value_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
