// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analog_keymap.proto

#include "analog_keymap.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace zmk {
namespace analog_keymap {
PROTOBUF_CONSTEXPR Request::Request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.request_type_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestDefaultTypeInternal() {}
  union {
    Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDefaultTypeInternal _Request_default_instance_;
PROTOBUF_CONSTEXPR Response::Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.response_type_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseDefaultTypeInternal() {}
  union {
    Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseDefaultTypeInternal _Response_default_instance_;
PROTOBUF_CONSTEXPR AnalogKeymap::AnalogKeymap(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.layers_)*/{}
  , /*decltype(_impl_.available_layers_)*/0u
  , /*decltype(_impl_.max_layer_name_length_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AnalogKeymapDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnalogKeymapDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnalogKeymapDefaultTypeInternal() {}
  union {
    AnalogKeymap _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnalogKeymapDefaultTypeInternal _AnalogKeymap_default_instance_;
PROTOBUF_CONSTEXPR AnalogLayer::AnalogLayer(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bindings_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AnalogLayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnalogLayerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnalogLayerDefaultTypeInternal() {}
  union {
    AnalogLayer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnalogLayerDefaultTypeInternal _AnalogLayer_default_instance_;
PROTOBUF_CONSTEXPR AnalogBehaviorBinding::AnalogBehaviorBinding(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.analog_behavior_id_)*/0u
  , /*decltype(_impl_.param0_)*/0
  , /*decltype(_impl_.param1_)*/0
  , /*decltype(_impl_.param2_)*/0
  , /*decltype(_impl_.param3_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AnalogBehaviorBindingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnalogBehaviorBindingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnalogBehaviorBindingDefaultTypeInternal() {}
  union {
    AnalogBehaviorBinding _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnalogBehaviorBindingDefaultTypeInternal _AnalogBehaviorBinding_default_instance_;
PROTOBUF_CONSTEXPR SetAnalogLayerBindingRequest::SetAnalogLayerBindingRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.analog_binding_)*/nullptr
  , /*decltype(_impl_.analog_layer_id_)*/0u
  , /*decltype(_impl_.key_position_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SetAnalogLayerBindingRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetAnalogLayerBindingRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetAnalogLayerBindingRequestDefaultTypeInternal() {}
  union {
    SetAnalogLayerBindingRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetAnalogLayerBindingRequestDefaultTypeInternal _SetAnalogLayerBindingRequest_default_instance_;
}  // namespace analog_keymap
}  // namespace zmk
static ::_pb::Metadata file_level_metadata_analog_5fkeymap_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_analog_5fkeymap_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_analog_5fkeymap_2eproto = nullptr;

const uint32_t TableStruct_analog_5fkeymap_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::Request, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::Request, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::Request, _impl_.request_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::Response, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::Response, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::Response, _impl_.response_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogKeymap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogKeymap, _impl_.layers_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogKeymap, _impl_.available_layers_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogKeymap, _impl_.max_layer_name_length_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogLayer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogLayer, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogLayer, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogLayer, _impl_.bindings_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogBehaviorBinding, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogBehaviorBinding, _impl_.analog_behavior_id_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogBehaviorBinding, _impl_.param0_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogBehaviorBinding, _impl_.param1_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogBehaviorBinding, _impl_.param2_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::AnalogBehaviorBinding, _impl_.param3_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::SetAnalogLayerBindingRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::SetAnalogLayerBindingRequest, _impl_.analog_layer_id_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::SetAnalogLayerBindingRequest, _impl_.key_position_),
  PROTOBUF_FIELD_OFFSET(::zmk::analog_keymap::SetAnalogLayerBindingRequest, _impl_.analog_binding_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::zmk::analog_keymap::Request)},
  { 9, -1, -1, sizeof(::zmk::analog_keymap::Response)},
  { 18, -1, -1, sizeof(::zmk::analog_keymap::AnalogKeymap)},
  { 27, -1, -1, sizeof(::zmk::analog_keymap::AnalogLayer)},
  { 36, -1, -1, sizeof(::zmk::analog_keymap::AnalogBehaviorBinding)},
  { 47, -1, -1, sizeof(::zmk::analog_keymap::SetAnalogLayerBindingRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::zmk::analog_keymap::_Request_default_instance_._instance,
  &::zmk::analog_keymap::_Response_default_instance_._instance,
  &::zmk::analog_keymap::_AnalogKeymap_default_instance_._instance,
  &::zmk::analog_keymap::_AnalogLayer_default_instance_._instance,
  &::zmk::analog_keymap::_AnalogBehaviorBinding_default_instance_._instance,
  &::zmk::analog_keymap::_SetAnalogLayerBindingRequest_default_instance_._instance,
};

const char descriptor_table_protodef_analog_5fkeymap_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023analog_keymap.proto\022\021zmk.analog_keymap"
  "\"\213\001\n\007Request\022\033\n\021get_analog_keymap\030\001 \001(\010H"
  "\000\022S\n\030set_analog_layer_binding\030@ \001(\0132/.zm"
  "k.analog_keymap.SetAnalogLayerBindingReq"
  "uestH\000B\016\n\014request_type\"\257\001\n\010Response\022<\n\021g"
  "et_analog_keymap\030\001 \001(\0132\037.zmk.analog_keym"
  "ap.AnalogKeymapH\000\022T\n\030set_analog_layer_bi"
  "nding\030@ \001(\01620.zmk.analog_keymap.SetAnalo"
  "gLayerBindingResponseH\000B\017\n\rresponse_type"
  "\"w\n\014AnalogKeymap\022.\n\006layers\030\001 \003(\0132\036.zmk.a"
  "nalog_keymap.AnalogLayer\022\030\n\020available_la"
  "yers\030\002 \001(\r\022\035\n\025max_layer_name_length\030\003 \001("
  "\r\"c\n\013AnalogLayer\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001"
  "(\t\022:\n\010bindings\030\003 \003(\0132(.zmk.analog_keymap"
  ".AnalogBehaviorBinding\"s\n\025AnalogBehavior"
  "Binding\022\032\n\022analog_behavior_id\030\001 \001(\r\022\016\n\006p"
  "aram0\030\002 \001(\021\022\016\n\006param1\030\003 \001(\021\022\016\n\006param2\030\004 "
  "\001(\021\022\016\n\006param3\030\005 \001(\021\"\217\001\n\034SetAnalogLayerBi"
  "ndingRequest\022\027\n\017analog_layer_id\030\001 \001(\r\022\024\n"
  "\014key_position\030\002 \001(\005\022@\n\016analog_binding\030\003 "
  "\001(\0132(.zmk.analog_keymap.AnalogBehaviorBi"
  "nding*\343\001\n\035SetAnalogLayerBindingResponse\022"
  "$\n SET_ANALOG_LAYER_BINDING_RESP_OK\020\000\0222\n"
  ".SET_ANALOG_LAYER_BINDING_RESP_INVALID_L"
  "OCATION\020\001\0222\n.SET_ANALOG_LAYER_BINDING_RE"
  "SP_INVALID_BEHAVIOR\020\002\0224\n0SET_ANALOG_LAYE"
  "R_BINDING_RESP_INVALID_PARAMETERS\020\003b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_analog_5fkeymap_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_analog_5fkeymap_2eproto = {
    false, false, 1083, descriptor_table_protodef_analog_5fkeymap_2eproto,
    "analog_keymap.proto",
    &descriptor_table_analog_5fkeymap_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_analog_5fkeymap_2eproto::offsets,
    file_level_metadata_analog_5fkeymap_2eproto, file_level_enum_descriptors_analog_5fkeymap_2eproto,
    file_level_service_descriptors_analog_5fkeymap_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_analog_5fkeymap_2eproto_getter() {
  return &descriptor_table_analog_5fkeymap_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_analog_5fkeymap_2eproto(&descriptor_table_analog_5fkeymap_2eproto);
namespace zmk {
namespace analog_keymap {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SetAnalogLayerBindingResponse_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_analog_5fkeymap_2eproto);
  return file_level_enum_descriptors_analog_5fkeymap_2eproto[0];
}
bool SetAnalogLayerBindingResponse_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Request::_Internal {
 public:
  static const ::zmk::analog_keymap::SetAnalogLayerBindingRequest& set_analog_layer_binding(const Request* msg);
};

const ::zmk::analog_keymap::SetAnalogLayerBindingRequest&
Request::_Internal::set_analog_layer_binding(const Request* msg) {
  return *msg->_impl_.request_type_.set_analog_layer_binding_;
}
void Request::set_allocated_set_analog_layer_binding(::zmk::analog_keymap::SetAnalogLayerBindingRequest* set_analog_layer_binding) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_request_type();
  if (set_analog_layer_binding) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(set_analog_layer_binding);
    if (message_arena != submessage_arena) {
      set_analog_layer_binding = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, set_analog_layer_binding, submessage_arena);
    }
    set_has_set_analog_layer_binding();
    _impl_.request_type_.set_analog_layer_binding_ = set_analog_layer_binding;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.analog_keymap.Request.set_analog_layer_binding)
}
Request::Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.analog_keymap.Request)
}
Request::Request(const Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.request_type_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_request_type();
  switch (from.request_type_case()) {
    case kGetAnalogKeymap: {
      _this->_internal_set_get_analog_keymap(from._internal_get_analog_keymap());
      break;
    }
    case kSetAnalogLayerBinding: {
      _this->_internal_mutable_set_analog_layer_binding()->::zmk::analog_keymap::SetAnalogLayerBindingRequest::MergeFrom(
          from._internal_set_analog_layer_binding());
      break;
    }
    case REQUEST_TYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:zmk.analog_keymap.Request)
}

inline void Request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.request_type_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_request_type();
}

Request::~Request() {
  // @@protoc_insertion_point(destructor:zmk.analog_keymap.Request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_request_type()) {
    clear_request_type();
  }
}

void Request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Request::clear_request_type() {
// @@protoc_insertion_point(one_of_clear_start:zmk.analog_keymap.Request)
  switch (request_type_case()) {
    case kGetAnalogKeymap: {
      // No need to clear
      break;
    }
    case kSetAnalogLayerBinding: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.request_type_.set_analog_layer_binding_;
      }
      break;
    }
    case REQUEST_TYPE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = REQUEST_TYPE_NOT_SET;
}


void Request::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.analog_keymap.Request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_request_type();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool get_analog_keymap = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _internal_set_get_analog_keymap(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.analog_keymap.SetAnalogLayerBindingRequest set_analog_layer_binding = 64;
      case 64:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 2)) {
          ptr = ctx->ParseMessage(_internal_mutable_set_analog_layer_binding(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.analog_keymap.Request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool get_analog_keymap = 1;
  if (_internal_has_get_analog_keymap()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_get_analog_keymap(), target);
  }

  // .zmk.analog_keymap.SetAnalogLayerBindingRequest set_analog_layer_binding = 64;
  if (_internal_has_set_analog_layer_binding()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(64, _Internal::set_analog_layer_binding(this),
        _Internal::set_analog_layer_binding(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.analog_keymap.Request)
  return target;
}

size_t Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.analog_keymap.Request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (request_type_case()) {
    // bool get_analog_keymap = 1;
    case kGetAnalogKeymap: {
      total_size += 1 + 1;
      break;
    }
    // .zmk.analog_keymap.SetAnalogLayerBindingRequest set_analog_layer_binding = 64;
    case kSetAnalogLayerBinding: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.request_type_.set_analog_layer_binding_);
      break;
    }
    case REQUEST_TYPE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Request::GetClassData() const { return &_class_data_; }


void Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Request*>(&to_msg);
  auto& from = static_cast<const Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.analog_keymap.Request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.request_type_case()) {
    case kGetAnalogKeymap: {
      _this->_internal_set_get_analog_keymap(from._internal_get_analog_keymap());
      break;
    }
    case kSetAnalogLayerBinding: {
      _this->_internal_mutable_set_analog_layer_binding()->::zmk::analog_keymap::SetAnalogLayerBindingRequest::MergeFrom(
          from._internal_set_analog_layer_binding());
      break;
    }
    case REQUEST_TYPE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request::CopyFrom(const Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.analog_keymap.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {
  return true;
}

void Request::InternalSwap(Request* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.request_type_, other->_impl_.request_type_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_analog_5fkeymap_2eproto_getter, &descriptor_table_analog_5fkeymap_2eproto_once,
      file_level_metadata_analog_5fkeymap_2eproto[0]);
}

// ===================================================================

class Response::_Internal {
 public:
  static const ::zmk::analog_keymap::AnalogKeymap& get_analog_keymap(const Response* msg);
};

const ::zmk::analog_keymap::AnalogKeymap&
Response::_Internal::get_analog_keymap(const Response* msg) {
  return *msg->_impl_.response_type_.get_analog_keymap_;
}
void Response::set_allocated_get_analog_keymap(::zmk::analog_keymap::AnalogKeymap* get_analog_keymap) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_response_type();
  if (get_analog_keymap) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(get_analog_keymap);
    if (message_arena != submessage_arena) {
      get_analog_keymap = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, get_analog_keymap, submessage_arena);
    }
    set_has_get_analog_keymap();
    _impl_.response_type_.get_analog_keymap_ = get_analog_keymap;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.analog_keymap.Response.get_analog_keymap)
}
Response::Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.analog_keymap.Response)
}
Response::Response(const Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.response_type_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_response_type();
  switch (from.response_type_case()) {
    case kGetAnalogKeymap: {
      _this->_internal_mutable_get_analog_keymap()->::zmk::analog_keymap::AnalogKeymap::MergeFrom(
          from._internal_get_analog_keymap());
      break;
    }
    case kSetAnalogLayerBinding: {
      _this->_internal_set_set_analog_layer_binding(from._internal_set_analog_layer_binding());
      break;
    }
    case RESPONSE_TYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:zmk.analog_keymap.Response)
}

inline void Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.response_type_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_response_type();
}

Response::~Response() {
  // @@protoc_insertion_point(destructor:zmk.analog_keymap.Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_response_type()) {
    clear_response_type();
  }
}

void Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Response::clear_response_type() {
// @@protoc_insertion_point(one_of_clear_start:zmk.analog_keymap.Response)
  switch (response_type_case()) {
    case kGetAnalogKeymap: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.response_type_.get_analog_keymap_;
      }
      break;
    }
    case kSetAnalogLayerBinding: {
      // No need to clear
      break;
    }
    case RESPONSE_TYPE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = RESPONSE_TYPE_NOT_SET;
}


void Response::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.analog_keymap.Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_response_type();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .zmk.analog_keymap.AnalogKeymap get_analog_keymap = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_get_analog_keymap(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.analog_keymap.SetAnalogLayerBindingResponse set_analog_layer_binding = 64;
      case 64:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 0)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_set_analog_layer_binding(static_cast<::zmk::analog_keymap::SetAnalogLayerBindingResponse>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.analog_keymap.Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .zmk.analog_keymap.AnalogKeymap get_analog_keymap = 1;
  if (_internal_has_get_analog_keymap()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::get_analog_keymap(this),
        _Internal::get_analog_keymap(this).GetCachedSize(), target, stream);
  }

  // .zmk.analog_keymap.SetAnalogLayerBindingResponse set_analog_layer_binding = 64;
  if (_internal_has_set_analog_layer_binding()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      64, this->_internal_set_analog_layer_binding(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.analog_keymap.Response)
  return target;
}

size_t Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.analog_keymap.Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (response_type_case()) {
    // .zmk.analog_keymap.AnalogKeymap get_analog_keymap = 1;
    case kGetAnalogKeymap: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.response_type_.get_analog_keymap_);
      break;
    }
    // .zmk.analog_keymap.SetAnalogLayerBindingResponse set_analog_layer_binding = 64;
    case kSetAnalogLayerBinding: {
      total_size += 2 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_set_analog_layer_binding());
      break;
    }
    case RESPONSE_TYPE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Response::GetClassData() const { return &_class_data_; }


void Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Response*>(&to_msg);
  auto& from = static_cast<const Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.analog_keymap.Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.response_type_case()) {
    case kGetAnalogKeymap: {
      _this->_internal_mutable_get_analog_keymap()->::zmk::analog_keymap::AnalogKeymap::MergeFrom(
          from._internal_get_analog_keymap());
      break;
    }
    case kSetAnalogLayerBinding: {
      _this->_internal_set_set_analog_layer_binding(from._internal_set_analog_layer_binding());
      break;
    }
    case RESPONSE_TYPE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Response::CopyFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.analog_keymap.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response::IsInitialized() const {
  return true;
}

void Response::InternalSwap(Response* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.response_type_, other->_impl_.response_type_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_analog_5fkeymap_2eproto_getter, &descriptor_table_analog_5fkeymap_2eproto_once,
      file_level_metadata_analog_5fkeymap_2eproto[1]);
}

// ===================================================================

class AnalogKeymap::_Internal {
 public:
};

AnalogKeymap::AnalogKeymap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.analog_keymap.AnalogKeymap)
}
AnalogKeymap::AnalogKeymap(const AnalogKeymap& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AnalogKeymap* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.layers_){from._impl_.layers_}
    , decltype(_impl_.available_layers_){}
    , decltype(_impl_.max_layer_name_length_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.available_layers_, &from._impl_.available_layers_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_layer_name_length_) -
    reinterpret_cast<char*>(&_impl_.available_layers_)) + sizeof(_impl_.max_layer_name_length_));
  // @@protoc_insertion_point(copy_constructor:zmk.analog_keymap.AnalogKeymap)
}

inline void AnalogKeymap::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.layers_){arena}
    , decltype(_impl_.available_layers_){0u}
    , decltype(_impl_.max_layer_name_length_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AnalogKeymap::~AnalogKeymap() {
  // @@protoc_insertion_point(destructor:zmk.analog_keymap.AnalogKeymap)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AnalogKeymap::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.layers_.~RepeatedPtrField();
}

void AnalogKeymap::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AnalogKeymap::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.analog_keymap.AnalogKeymap)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.layers_.Clear();
  ::memset(&_impl_.available_layers_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.max_layer_name_length_) -
      reinterpret_cast<char*>(&_impl_.available_layers_)) + sizeof(_impl_.max_layer_name_length_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AnalogKeymap::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .zmk.analog_keymap.AnalogLayer layers = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_layers(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 available_layers = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.available_layers_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 max_layer_name_length = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.max_layer_name_length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AnalogKeymap::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.analog_keymap.AnalogKeymap)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .zmk.analog_keymap.AnalogLayer layers = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_layers_size()); i < n; i++) {
    const auto& repfield = this->_internal_layers(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // uint32 available_layers = 2;
  if (this->_internal_available_layers() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_available_layers(), target);
  }

  // uint32 max_layer_name_length = 3;
  if (this->_internal_max_layer_name_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_max_layer_name_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.analog_keymap.AnalogKeymap)
  return target;
}

size_t AnalogKeymap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.analog_keymap.AnalogKeymap)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .zmk.analog_keymap.AnalogLayer layers = 1;
  total_size += 1UL * this->_internal_layers_size();
  for (const auto& msg : this->_impl_.layers_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 available_layers = 2;
  if (this->_internal_available_layers() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_available_layers());
  }

  // uint32 max_layer_name_length = 3;
  if (this->_internal_max_layer_name_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_max_layer_name_length());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AnalogKeymap::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AnalogKeymap::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AnalogKeymap::GetClassData() const { return &_class_data_; }


void AnalogKeymap::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AnalogKeymap*>(&to_msg);
  auto& from = static_cast<const AnalogKeymap&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.analog_keymap.AnalogKeymap)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.layers_.MergeFrom(from._impl_.layers_);
  if (from._internal_available_layers() != 0) {
    _this->_internal_set_available_layers(from._internal_available_layers());
  }
  if (from._internal_max_layer_name_length() != 0) {
    _this->_internal_set_max_layer_name_length(from._internal_max_layer_name_length());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AnalogKeymap::CopyFrom(const AnalogKeymap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.analog_keymap.AnalogKeymap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnalogKeymap::IsInitialized() const {
  return true;
}

void AnalogKeymap::InternalSwap(AnalogKeymap* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.layers_.InternalSwap(&other->_impl_.layers_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnalogKeymap, _impl_.max_layer_name_length_)
      + sizeof(AnalogKeymap::_impl_.max_layer_name_length_)
      - PROTOBUF_FIELD_OFFSET(AnalogKeymap, _impl_.available_layers_)>(
          reinterpret_cast<char*>(&_impl_.available_layers_),
          reinterpret_cast<char*>(&other->_impl_.available_layers_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AnalogKeymap::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_analog_5fkeymap_2eproto_getter, &descriptor_table_analog_5fkeymap_2eproto_once,
      file_level_metadata_analog_5fkeymap_2eproto[2]);
}

// ===================================================================

class AnalogLayer::_Internal {
 public:
};

AnalogLayer::AnalogLayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.analog_keymap.AnalogLayer)
}
AnalogLayer::AnalogLayer(const AnalogLayer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AnalogLayer* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bindings_){from._impl_.bindings_}
    , decltype(_impl_.name_){}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:zmk.analog_keymap.AnalogLayer)
}

inline void AnalogLayer::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bindings_){arena}
    , decltype(_impl_.name_){}
    , decltype(_impl_.id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AnalogLayer::~AnalogLayer() {
  // @@protoc_insertion_point(destructor:zmk.analog_keymap.AnalogLayer)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AnalogLayer::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bindings_.~RepeatedPtrField();
  _impl_.name_.Destroy();
}

void AnalogLayer::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AnalogLayer::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.analog_keymap.AnalogLayer)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bindings_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AnalogLayer::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "zmk.analog_keymap.AnalogLayer.name"));
        } else
          goto handle_unusual;
        continue;
      // repeated .zmk.analog_keymap.AnalogBehaviorBinding bindings = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_bindings(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AnalogLayer::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.analog_keymap.AnalogLayer)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "zmk.analog_keymap.AnalogLayer.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // repeated .zmk.analog_keymap.AnalogBehaviorBinding bindings = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_bindings_size()); i < n; i++) {
    const auto& repfield = this->_internal_bindings(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.analog_keymap.AnalogLayer)
  return target;
}

size_t AnalogLayer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.analog_keymap.AnalogLayer)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .zmk.analog_keymap.AnalogBehaviorBinding bindings = 3;
  total_size += 1UL * this->_internal_bindings_size();
  for (const auto& msg : this->_impl_.bindings_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AnalogLayer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AnalogLayer::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AnalogLayer::GetClassData() const { return &_class_data_; }


void AnalogLayer::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AnalogLayer*>(&to_msg);
  auto& from = static_cast<const AnalogLayer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.analog_keymap.AnalogLayer)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.bindings_.MergeFrom(from._impl_.bindings_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AnalogLayer::CopyFrom(const AnalogLayer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.analog_keymap.AnalogLayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnalogLayer::IsInitialized() const {
  return true;
}

void AnalogLayer::InternalSwap(AnalogLayer* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.bindings_.InternalSwap(&other->_impl_.bindings_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AnalogLayer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_analog_5fkeymap_2eproto_getter, &descriptor_table_analog_5fkeymap_2eproto_once,
      file_level_metadata_analog_5fkeymap_2eproto[3]);
}

// ===================================================================

class AnalogBehaviorBinding::_Internal {
 public:
};

AnalogBehaviorBinding::AnalogBehaviorBinding(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.analog_keymap.AnalogBehaviorBinding)
}
AnalogBehaviorBinding::AnalogBehaviorBinding(const AnalogBehaviorBinding& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AnalogBehaviorBinding* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.analog_behavior_id_){}
    , decltype(_impl_.param0_){}
    , decltype(_impl_.param1_){}
    , decltype(_impl_.param2_){}
    , decltype(_impl_.param3_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.analog_behavior_id_, &from._impl_.analog_behavior_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.param3_) -
    reinterpret_cast<char*>(&_impl_.analog_behavior_id_)) + sizeof(_impl_.param3_));
  // @@protoc_insertion_point(copy_constructor:zmk.analog_keymap.AnalogBehaviorBinding)
}

inline void AnalogBehaviorBinding::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.analog_behavior_id_){0u}
    , decltype(_impl_.param0_){0}
    , decltype(_impl_.param1_){0}
    , decltype(_impl_.param2_){0}
    , decltype(_impl_.param3_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AnalogBehaviorBinding::~AnalogBehaviorBinding() {
  // @@protoc_insertion_point(destructor:zmk.analog_keymap.AnalogBehaviorBinding)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AnalogBehaviorBinding::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AnalogBehaviorBinding::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AnalogBehaviorBinding::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.analog_keymap.AnalogBehaviorBinding)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.analog_behavior_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.param3_) -
      reinterpret_cast<char*>(&_impl_.analog_behavior_id_)) + sizeof(_impl_.param3_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AnalogBehaviorBinding::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 analog_behavior_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.analog_behavior_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 param0 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.param0_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 param1 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.param1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 param2 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.param2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 param3 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.param3_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AnalogBehaviorBinding::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.analog_keymap.AnalogBehaviorBinding)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 analog_behavior_id = 1;
  if (this->_internal_analog_behavior_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_analog_behavior_id(), target);
  }

  // sint32 param0 = 2;
  if (this->_internal_param0() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(2, this->_internal_param0(), target);
  }

  // sint32 param1 = 3;
  if (this->_internal_param1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(3, this->_internal_param1(), target);
  }

  // sint32 param2 = 4;
  if (this->_internal_param2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(4, this->_internal_param2(), target);
  }

  // sint32 param3 = 5;
  if (this->_internal_param3() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(5, this->_internal_param3(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.analog_keymap.AnalogBehaviorBinding)
  return target;
}

size_t AnalogBehaviorBinding::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.analog_keymap.AnalogBehaviorBinding)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 analog_behavior_id = 1;
  if (this->_internal_analog_behavior_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_analog_behavior_id());
  }

  // sint32 param0 = 2;
  if (this->_internal_param0() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_param0());
  }

  // sint32 param1 = 3;
  if (this->_internal_param1() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_param1());
  }

  // sint32 param2 = 4;
  if (this->_internal_param2() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_param2());
  }

  // sint32 param3 = 5;
  if (this->_internal_param3() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_param3());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AnalogBehaviorBinding::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AnalogBehaviorBinding::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AnalogBehaviorBinding::GetClassData() const { return &_class_data_; }


void AnalogBehaviorBinding::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AnalogBehaviorBinding*>(&to_msg);
  auto& from = static_cast<const AnalogBehaviorBinding&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.analog_keymap.AnalogBehaviorBinding)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_analog_behavior_id() != 0) {
    _this->_internal_set_analog_behavior_id(from._internal_analog_behavior_id());
  }
  if (from._internal_param0() != 0) {
    _this->_internal_set_param0(from._internal_param0());
  }
  if (from._internal_param1() != 0) {
    _this->_internal_set_param1(from._internal_param1());
  }
  if (from._internal_param2() != 0) {
    _this->_internal_set_param2(from._internal_param2());
  }
  if (from._internal_param3() != 0) {
    _this->_internal_set_param3(from._internal_param3());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AnalogBehaviorBinding::CopyFrom(const AnalogBehaviorBinding& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.analog_keymap.AnalogBehaviorBinding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnalogBehaviorBinding::IsInitialized() const {
  return true;
}

void AnalogBehaviorBinding::InternalSwap(AnalogBehaviorBinding* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnalogBehaviorBinding, _impl_.param3_)
      + sizeof(AnalogBehaviorBinding::_impl_.param3_)
      - PROTOBUF_FIELD_OFFSET(AnalogBehaviorBinding, _impl_.analog_behavior_id_)>(
          reinterpret_cast<char*>(&_impl_.analog_behavior_id_),
          reinterpret_cast<char*>(&other->_impl_.analog_behavior_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AnalogBehaviorBinding::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_analog_5fkeymap_2eproto_getter, &descriptor_table_analog_5fkeymap_2eproto_once,
      file_level_metadata_analog_5fkeymap_2eproto[4]);
}

// ===================================================================

class SetAnalogLayerBindingRequest::_Internal {
 public:
  static const ::zmk::analog_keymap::AnalogBehaviorBinding& analog_binding(const SetAnalogLayerBindingRequest* msg);
};

const ::zmk::analog_keymap::AnalogBehaviorBinding&
SetAnalogLayerBindingRequest::_Internal::analog_binding(const SetAnalogLayerBindingRequest* msg) {
  return *msg->_impl_.analog_binding_;
}
SetAnalogLayerBindingRequest::SetAnalogLayerBindingRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.analog_keymap.SetAnalogLayerBindingRequest)
}
SetAnalogLayerBindingRequest::SetAnalogLayerBindingRequest(const SetAnalogLayerBindingRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SetAnalogLayerBindingRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.analog_binding_){nullptr}
    , decltype(_impl_.analog_layer_id_){}
    , decltype(_impl_.key_position_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_analog_binding()) {
    _this->_impl_.analog_binding_ = new ::zmk::analog_keymap::AnalogBehaviorBinding(*from._impl_.analog_binding_);
  }
  ::memcpy(&_impl_.analog_layer_id_, &from._impl_.analog_layer_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.key_position_) -
    reinterpret_cast<char*>(&_impl_.analog_layer_id_)) + sizeof(_impl_.key_position_));
  // @@protoc_insertion_point(copy_constructor:zmk.analog_keymap.SetAnalogLayerBindingRequest)
}

inline void SetAnalogLayerBindingRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.analog_binding_){nullptr}
    , decltype(_impl_.analog_layer_id_){0u}
    , decltype(_impl_.key_position_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SetAnalogLayerBindingRequest::~SetAnalogLayerBindingRequest() {
  // @@protoc_insertion_point(destructor:zmk.analog_keymap.SetAnalogLayerBindingRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SetAnalogLayerBindingRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.analog_binding_;
}

void SetAnalogLayerBindingRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SetAnalogLayerBindingRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.analog_keymap.SetAnalogLayerBindingRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.analog_binding_ != nullptr) {
    delete _impl_.analog_binding_;
  }
  _impl_.analog_binding_ = nullptr;
  ::memset(&_impl_.analog_layer_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.key_position_) -
      reinterpret_cast<char*>(&_impl_.analog_layer_id_)) + sizeof(_impl_.key_position_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetAnalogLayerBindingRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 analog_layer_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.analog_layer_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 key_position = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.key_position_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.analog_keymap.AnalogBehaviorBinding analog_binding = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_analog_binding(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetAnalogLayerBindingRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.analog_keymap.SetAnalogLayerBindingRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 analog_layer_id = 1;
  if (this->_internal_analog_layer_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_analog_layer_id(), target);
  }

  // int32 key_position = 2;
  if (this->_internal_key_position() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_key_position(), target);
  }

  // .zmk.analog_keymap.AnalogBehaviorBinding analog_binding = 3;
  if (this->_internal_has_analog_binding()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::analog_binding(this),
        _Internal::analog_binding(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.analog_keymap.SetAnalogLayerBindingRequest)
  return target;
}

size_t SetAnalogLayerBindingRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.analog_keymap.SetAnalogLayerBindingRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .zmk.analog_keymap.AnalogBehaviorBinding analog_binding = 3;
  if (this->_internal_has_analog_binding()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.analog_binding_);
  }

  // uint32 analog_layer_id = 1;
  if (this->_internal_analog_layer_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_analog_layer_id());
  }

  // int32 key_position = 2;
  if (this->_internal_key_position() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_key_position());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetAnalogLayerBindingRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SetAnalogLayerBindingRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetAnalogLayerBindingRequest::GetClassData() const { return &_class_data_; }


void SetAnalogLayerBindingRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SetAnalogLayerBindingRequest*>(&to_msg);
  auto& from = static_cast<const SetAnalogLayerBindingRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.analog_keymap.SetAnalogLayerBindingRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_analog_binding()) {
    _this->_internal_mutable_analog_binding()->::zmk::analog_keymap::AnalogBehaviorBinding::MergeFrom(
        from._internal_analog_binding());
  }
  if (from._internal_analog_layer_id() != 0) {
    _this->_internal_set_analog_layer_id(from._internal_analog_layer_id());
  }
  if (from._internal_key_position() != 0) {
    _this->_internal_set_key_position(from._internal_key_position());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetAnalogLayerBindingRequest::CopyFrom(const SetAnalogLayerBindingRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.analog_keymap.SetAnalogLayerBindingRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetAnalogLayerBindingRequest::IsInitialized() const {
  return true;
}

void SetAnalogLayerBindingRequest::InternalSwap(SetAnalogLayerBindingRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SetAnalogLayerBindingRequest, _impl_.key_position_)
      + sizeof(SetAnalogLayerBindingRequest::_impl_.key_position_)
      - PROTOBUF_FIELD_OFFSET(SetAnalogLayerBindingRequest, _impl_.analog_binding_)>(
          reinterpret_cast<char*>(&_impl_.analog_binding_),
          reinterpret_cast<char*>(&other->_impl_.analog_binding_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SetAnalogLayerBindingRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_analog_5fkeymap_2eproto_getter, &descriptor_table_analog_5fkeymap_2eproto_once,
      file_level_metadata_analog_5fkeymap_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace analog_keymap
}  // namespace zmk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::zmk::analog_keymap::Request*
Arena::CreateMaybeMessage< ::zmk::analog_keymap::Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::analog_keymap::Request >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::analog_keymap::Response*
Arena::CreateMaybeMessage< ::zmk::analog_keymap::Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::analog_keymap::Response >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::analog_keymap::AnalogKeymap*
Arena::CreateMaybeMessage< ::zmk::analog_keymap::AnalogKeymap >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::analog_keymap::AnalogKeymap >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::analog_keymap::AnalogLayer*
Arena::CreateMaybeMessage< ::zmk::analog_keymap::AnalogLayer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::analog_keymap::AnalogLayer >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::analog_keymap::AnalogBehaviorBinding*
Arena::CreateMaybeMessage< ::zmk::analog_keymap::AnalogBehaviorBinding >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::analog_keymap::AnalogBehaviorBinding >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::analog_keymap::SetAnalogLayerBindingRequest*
Arena::CreateMaybeMessage< ::zmk::analog_keymap::SetAnalogLayerBindingRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::analog_keymap::SetAnalogLayerBindingRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
