// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_core_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_core_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_core_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_core_2eproto;
namespace zmk {
namespace core {
class GetDeviceInfoResponse;
struct GetDeviceInfoResponseDefaultTypeInternal;
extern GetDeviceInfoResponseDefaultTypeInternal _GetDeviceInfoResponse_default_instance_;
class Notification;
struct NotificationDefaultTypeInternal;
extern NotificationDefaultTypeInternal _Notification_default_instance_;
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace core
}  // namespace zmk
PROTOBUF_NAMESPACE_OPEN
template<> ::zmk::core::GetDeviceInfoResponse* Arena::CreateMaybeMessage<::zmk::core::GetDeviceInfoResponse>(Arena*);
template<> ::zmk::core::Notification* Arena::CreateMaybeMessage<::zmk::core::Notification>(Arena*);
template<> ::zmk::core::Request* Arena::CreateMaybeMessage<::zmk::core::Request>(Arena*);
template<> ::zmk::core::Response* Arena::CreateMaybeMessage<::zmk::core::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace zmk {
namespace core {

enum LockState : int {
  ZMK_STUDIO_CORE_LOCK_STATE_LOCKED = 0,
  ZMK_STUDIO_CORE_LOCK_STATE_UNLOCKED = 1,
  LockState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LockState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LockState_IsValid(int value);
constexpr LockState LockState_MIN = ZMK_STUDIO_CORE_LOCK_STATE_LOCKED;
constexpr LockState LockState_MAX = ZMK_STUDIO_CORE_LOCK_STATE_UNLOCKED;
constexpr int LockState_ARRAYSIZE = LockState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LockState_descriptor();
template<typename T>
inline const std::string& LockState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LockState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LockState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LockState_descriptor(), enum_t_value);
}
inline bool LockState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LockState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LockState>(
    LockState_descriptor(), name, value);
}
// ===================================================================

class Request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zmk.core.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() override;
  explicit PROTOBUF_CONSTEXPR Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *internal_default_instance();
  }
  enum RequestTypeCase {
    kGetDeviceInfo = 1,
    kGetLockState = 2,
    kLock = 3,
    kResetSettings = 4,
    REQUEST_TYPE_NOT_SET = 0,
  };

  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Request& from) {
    Request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zmk.core.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGetDeviceInfoFieldNumber = 1,
    kGetLockStateFieldNumber = 2,
    kLockFieldNumber = 3,
    kResetSettingsFieldNumber = 4,
  };
  // bool get_device_info = 1;
  bool has_get_device_info() const;
  private:
  bool _internal_has_get_device_info() const;
  public:
  void clear_get_device_info();
  bool get_device_info() const;
  void set_get_device_info(bool value);
  private:
  bool _internal_get_device_info() const;
  void _internal_set_get_device_info(bool value);
  public:

  // bool get_lock_state = 2;
  bool has_get_lock_state() const;
  private:
  bool _internal_has_get_lock_state() const;
  public:
  void clear_get_lock_state();
  bool get_lock_state() const;
  void set_get_lock_state(bool value);
  private:
  bool _internal_get_lock_state() const;
  void _internal_set_get_lock_state(bool value);
  public:

  // bool lock = 3;
  bool has_lock() const;
  private:
  bool _internal_has_lock() const;
  public:
  void clear_lock();
  bool lock() const;
  void set_lock(bool value);
  private:
  bool _internal_lock() const;
  void _internal_set_lock(bool value);
  public:

  // bool reset_settings = 4;
  bool has_reset_settings() const;
  private:
  bool _internal_has_reset_settings() const;
  public:
  void clear_reset_settings();
  bool reset_settings() const;
  void set_reset_settings(bool value);
  private:
  bool _internal_reset_settings() const;
  void _internal_set_reset_settings(bool value);
  public:

  void clear_request_type();
  RequestTypeCase request_type_case() const;
  // @@protoc_insertion_point(class_scope:zmk.core.Request)
 private:
  class _Internal;
  void set_has_get_device_info();
  void set_has_get_lock_state();
  void set_has_lock();
  void set_has_reset_settings();

  inline bool has_request_type() const;
  inline void clear_has_request_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union RequestTypeUnion {
      constexpr RequestTypeUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      bool get_device_info_;
      bool get_lock_state_;
      bool lock_;
      bool reset_settings_;
    } request_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};
// -------------------------------------------------------------------

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zmk.core.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  enum ResponseTypeCase {
    kGetDeviceInfo = 1,
    kGetLockState = 2,
    kResetSettings = 4,
    RESPONSE_TYPE_NOT_SET = 0,
  };

  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response& from) {
    Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zmk.core.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGetDeviceInfoFieldNumber = 1,
    kGetLockStateFieldNumber = 2,
    kResetSettingsFieldNumber = 4,
  };
  // .zmk.core.GetDeviceInfoResponse get_device_info = 1;
  bool has_get_device_info() const;
  private:
  bool _internal_has_get_device_info() const;
  public:
  void clear_get_device_info();
  const ::zmk::core::GetDeviceInfoResponse& get_device_info() const;
  PROTOBUF_NODISCARD ::zmk::core::GetDeviceInfoResponse* release_get_device_info();
  ::zmk::core::GetDeviceInfoResponse* mutable_get_device_info();
  void set_allocated_get_device_info(::zmk::core::GetDeviceInfoResponse* get_device_info);
  private:
  const ::zmk::core::GetDeviceInfoResponse& _internal_get_device_info() const;
  ::zmk::core::GetDeviceInfoResponse* _internal_mutable_get_device_info();
  public:
  void unsafe_arena_set_allocated_get_device_info(
      ::zmk::core::GetDeviceInfoResponse* get_device_info);
  ::zmk::core::GetDeviceInfoResponse* unsafe_arena_release_get_device_info();

  // .zmk.core.LockState get_lock_state = 2;
  bool has_get_lock_state() const;
  private:
  bool _internal_has_get_lock_state() const;
  public:
  void clear_get_lock_state();
  ::zmk::core::LockState get_lock_state() const;
  void set_get_lock_state(::zmk::core::LockState value);
  private:
  ::zmk::core::LockState _internal_get_lock_state() const;
  void _internal_set_get_lock_state(::zmk::core::LockState value);
  public:

  // bool reset_settings = 4;
  bool has_reset_settings() const;
  private:
  bool _internal_has_reset_settings() const;
  public:
  void clear_reset_settings();
  bool reset_settings() const;
  void set_reset_settings(bool value);
  private:
  bool _internal_reset_settings() const;
  void _internal_set_reset_settings(bool value);
  public:

  void clear_response_type();
  ResponseTypeCase response_type_case() const;
  // @@protoc_insertion_point(class_scope:zmk.core.Response)
 private:
  class _Internal;
  void set_has_get_device_info();
  void set_has_get_lock_state();
  void set_has_reset_settings();

  inline bool has_response_type() const;
  inline void clear_has_response_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ResponseTypeUnion {
      constexpr ResponseTypeUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::zmk::core::GetDeviceInfoResponse* get_device_info_;
      int get_lock_state_;
      bool reset_settings_;
    } response_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};
// -------------------------------------------------------------------

class GetDeviceInfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zmk.core.GetDeviceInfoResponse) */ {
 public:
  inline GetDeviceInfoResponse() : GetDeviceInfoResponse(nullptr) {}
  ~GetDeviceInfoResponse() override;
  explicit PROTOBUF_CONSTEXPR GetDeviceInfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetDeviceInfoResponse(const GetDeviceInfoResponse& from);
  GetDeviceInfoResponse(GetDeviceInfoResponse&& from) noexcept
    : GetDeviceInfoResponse() {
    *this = ::std::move(from);
  }

  inline GetDeviceInfoResponse& operator=(const GetDeviceInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDeviceInfoResponse& operator=(GetDeviceInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDeviceInfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetDeviceInfoResponse* internal_default_instance() {
    return reinterpret_cast<const GetDeviceInfoResponse*>(
               &_GetDeviceInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetDeviceInfoResponse& a, GetDeviceInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetDeviceInfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDeviceInfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDeviceInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetDeviceInfoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetDeviceInfoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetDeviceInfoResponse& from) {
    GetDeviceInfoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDeviceInfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zmk.core.GetDeviceInfoResponse";
  }
  protected:
  explicit GetDeviceInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kSerialNumberFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bytes serial_number = 2;
  void clear_serial_number();
  const std::string& serial_number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_serial_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_serial_number();
  PROTOBUF_NODISCARD std::string* release_serial_number();
  void set_allocated_serial_number(std::string* serial_number);
  private:
  const std::string& _internal_serial_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serial_number(const std::string& value);
  std::string* _internal_mutable_serial_number();
  public:

  // @@protoc_insertion_point(class_scope:zmk.core.GetDeviceInfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serial_number_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};
// -------------------------------------------------------------------

class Notification final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zmk.core.Notification) */ {
 public:
  inline Notification() : Notification(nullptr) {}
  ~Notification() override;
  explicit PROTOBUF_CONSTEXPR Notification(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Notification(const Notification& from);
  Notification(Notification&& from) noexcept
    : Notification() {
    *this = ::std::move(from);
  }

  inline Notification& operator=(const Notification& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification& operator=(Notification&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Notification& default_instance() {
    return *internal_default_instance();
  }
  enum NotificationTypeCase {
    kLockStateChanged = 1,
    NOTIFICATION_TYPE_NOT_SET = 0,
  };

  static inline const Notification* internal_default_instance() {
    return reinterpret_cast<const Notification*>(
               &_Notification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Notification& a, Notification& b) {
    a.Swap(&b);
  }
  inline void Swap(Notification* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Notification* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Notification>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Notification& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Notification& from) {
    Notification::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Notification* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zmk.core.Notification";
  }
  protected:
  explicit Notification(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLockStateChangedFieldNumber = 1,
  };
  // .zmk.core.LockState lock_state_changed = 1;
  bool has_lock_state_changed() const;
  private:
  bool _internal_has_lock_state_changed() const;
  public:
  void clear_lock_state_changed();
  ::zmk::core::LockState lock_state_changed() const;
  void set_lock_state_changed(::zmk::core::LockState value);
  private:
  ::zmk::core::LockState _internal_lock_state_changed() const;
  void _internal_set_lock_state_changed(::zmk::core::LockState value);
  public:

  void clear_notification_type();
  NotificationTypeCase notification_type_case() const;
  // @@protoc_insertion_point(class_scope:zmk.core.Notification)
 private:
  class _Internal;
  void set_has_lock_state_changed();

  inline bool has_notification_type() const;
  inline void clear_has_notification_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union NotificationTypeUnion {
      constexpr NotificationTypeUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      int lock_state_changed_;
    } notification_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// bool get_device_info = 1;
inline bool Request::_internal_has_get_device_info() const {
  return request_type_case() == kGetDeviceInfo;
}
inline bool Request::has_get_device_info() const {
  return _internal_has_get_device_info();
}
inline void Request::set_has_get_device_info() {
  _impl_._oneof_case_[0] = kGetDeviceInfo;
}
inline void Request::clear_get_device_info() {
  if (_internal_has_get_device_info()) {
    _impl_.request_type_.get_device_info_ = false;
    clear_has_request_type();
  }
}
inline bool Request::_internal_get_device_info() const {
  if (_internal_has_get_device_info()) {
    return _impl_.request_type_.get_device_info_;
  }
  return false;
}
inline void Request::_internal_set_get_device_info(bool value) {
  if (!_internal_has_get_device_info()) {
    clear_request_type();
    set_has_get_device_info();
  }
  _impl_.request_type_.get_device_info_ = value;
}
inline bool Request::get_device_info() const {
  // @@protoc_insertion_point(field_get:zmk.core.Request.get_device_info)
  return _internal_get_device_info();
}
inline void Request::set_get_device_info(bool value) {
  _internal_set_get_device_info(value);
  // @@protoc_insertion_point(field_set:zmk.core.Request.get_device_info)
}

// bool get_lock_state = 2;
inline bool Request::_internal_has_get_lock_state() const {
  return request_type_case() == kGetLockState;
}
inline bool Request::has_get_lock_state() const {
  return _internal_has_get_lock_state();
}
inline void Request::set_has_get_lock_state() {
  _impl_._oneof_case_[0] = kGetLockState;
}
inline void Request::clear_get_lock_state() {
  if (_internal_has_get_lock_state()) {
    _impl_.request_type_.get_lock_state_ = false;
    clear_has_request_type();
  }
}
inline bool Request::_internal_get_lock_state() const {
  if (_internal_has_get_lock_state()) {
    return _impl_.request_type_.get_lock_state_;
  }
  return false;
}
inline void Request::_internal_set_get_lock_state(bool value) {
  if (!_internal_has_get_lock_state()) {
    clear_request_type();
    set_has_get_lock_state();
  }
  _impl_.request_type_.get_lock_state_ = value;
}
inline bool Request::get_lock_state() const {
  // @@protoc_insertion_point(field_get:zmk.core.Request.get_lock_state)
  return _internal_get_lock_state();
}
inline void Request::set_get_lock_state(bool value) {
  _internal_set_get_lock_state(value);
  // @@protoc_insertion_point(field_set:zmk.core.Request.get_lock_state)
}

// bool lock = 3;
inline bool Request::_internal_has_lock() const {
  return request_type_case() == kLock;
}
inline bool Request::has_lock() const {
  return _internal_has_lock();
}
inline void Request::set_has_lock() {
  _impl_._oneof_case_[0] = kLock;
}
inline void Request::clear_lock() {
  if (_internal_has_lock()) {
    _impl_.request_type_.lock_ = false;
    clear_has_request_type();
  }
}
inline bool Request::_internal_lock() const {
  if (_internal_has_lock()) {
    return _impl_.request_type_.lock_;
  }
  return false;
}
inline void Request::_internal_set_lock(bool value) {
  if (!_internal_has_lock()) {
    clear_request_type();
    set_has_lock();
  }
  _impl_.request_type_.lock_ = value;
}
inline bool Request::lock() const {
  // @@protoc_insertion_point(field_get:zmk.core.Request.lock)
  return _internal_lock();
}
inline void Request::set_lock(bool value) {
  _internal_set_lock(value);
  // @@protoc_insertion_point(field_set:zmk.core.Request.lock)
}

// bool reset_settings = 4;
inline bool Request::_internal_has_reset_settings() const {
  return request_type_case() == kResetSettings;
}
inline bool Request::has_reset_settings() const {
  return _internal_has_reset_settings();
}
inline void Request::set_has_reset_settings() {
  _impl_._oneof_case_[0] = kResetSettings;
}
inline void Request::clear_reset_settings() {
  if (_internal_has_reset_settings()) {
    _impl_.request_type_.reset_settings_ = false;
    clear_has_request_type();
  }
}
inline bool Request::_internal_reset_settings() const {
  if (_internal_has_reset_settings()) {
    return _impl_.request_type_.reset_settings_;
  }
  return false;
}
inline void Request::_internal_set_reset_settings(bool value) {
  if (!_internal_has_reset_settings()) {
    clear_request_type();
    set_has_reset_settings();
  }
  _impl_.request_type_.reset_settings_ = value;
}
inline bool Request::reset_settings() const {
  // @@protoc_insertion_point(field_get:zmk.core.Request.reset_settings)
  return _internal_reset_settings();
}
inline void Request::set_reset_settings(bool value) {
  _internal_set_reset_settings(value);
  // @@protoc_insertion_point(field_set:zmk.core.Request.reset_settings)
}

inline bool Request::has_request_type() const {
  return request_type_case() != REQUEST_TYPE_NOT_SET;
}
inline void Request::clear_has_request_type() {
  _impl_._oneof_case_[0] = REQUEST_TYPE_NOT_SET;
}
inline Request::RequestTypeCase Request::request_type_case() const {
  return Request::RequestTypeCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Response

// .zmk.core.GetDeviceInfoResponse get_device_info = 1;
inline bool Response::_internal_has_get_device_info() const {
  return response_type_case() == kGetDeviceInfo;
}
inline bool Response::has_get_device_info() const {
  return _internal_has_get_device_info();
}
inline void Response::set_has_get_device_info() {
  _impl_._oneof_case_[0] = kGetDeviceInfo;
}
inline void Response::clear_get_device_info() {
  if (_internal_has_get_device_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.response_type_.get_device_info_;
    }
    clear_has_response_type();
  }
}
inline ::zmk::core::GetDeviceInfoResponse* Response::release_get_device_info() {
  // @@protoc_insertion_point(field_release:zmk.core.Response.get_device_info)
  if (_internal_has_get_device_info()) {
    clear_has_response_type();
    ::zmk::core::GetDeviceInfoResponse* temp = _impl_.response_type_.get_device_info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_type_.get_device_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::zmk::core::GetDeviceInfoResponse& Response::_internal_get_device_info() const {
  return _internal_has_get_device_info()
      ? *_impl_.response_type_.get_device_info_
      : reinterpret_cast< ::zmk::core::GetDeviceInfoResponse&>(::zmk::core::_GetDeviceInfoResponse_default_instance_);
}
inline const ::zmk::core::GetDeviceInfoResponse& Response::get_device_info() const {
  // @@protoc_insertion_point(field_get:zmk.core.Response.get_device_info)
  return _internal_get_device_info();
}
inline ::zmk::core::GetDeviceInfoResponse* Response::unsafe_arena_release_get_device_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zmk.core.Response.get_device_info)
  if (_internal_has_get_device_info()) {
    clear_has_response_type();
    ::zmk::core::GetDeviceInfoResponse* temp = _impl_.response_type_.get_device_info_;
    _impl_.response_type_.get_device_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Response::unsafe_arena_set_allocated_get_device_info(::zmk::core::GetDeviceInfoResponse* get_device_info) {
  clear_response_type();
  if (get_device_info) {
    set_has_get_device_info();
    _impl_.response_type_.get_device_info_ = get_device_info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zmk.core.Response.get_device_info)
}
inline ::zmk::core::GetDeviceInfoResponse* Response::_internal_mutable_get_device_info() {
  if (!_internal_has_get_device_info()) {
    clear_response_type();
    set_has_get_device_info();
    _impl_.response_type_.get_device_info_ = CreateMaybeMessage< ::zmk::core::GetDeviceInfoResponse >(GetArenaForAllocation());
  }
  return _impl_.response_type_.get_device_info_;
}
inline ::zmk::core::GetDeviceInfoResponse* Response::mutable_get_device_info() {
  ::zmk::core::GetDeviceInfoResponse* _msg = _internal_mutable_get_device_info();
  // @@protoc_insertion_point(field_mutable:zmk.core.Response.get_device_info)
  return _msg;
}

// .zmk.core.LockState get_lock_state = 2;
inline bool Response::_internal_has_get_lock_state() const {
  return response_type_case() == kGetLockState;
}
inline bool Response::has_get_lock_state() const {
  return _internal_has_get_lock_state();
}
inline void Response::set_has_get_lock_state() {
  _impl_._oneof_case_[0] = kGetLockState;
}
inline void Response::clear_get_lock_state() {
  if (_internal_has_get_lock_state()) {
    _impl_.response_type_.get_lock_state_ = 0;
    clear_has_response_type();
  }
}
inline ::zmk::core::LockState Response::_internal_get_lock_state() const {
  if (_internal_has_get_lock_state()) {
    return static_cast< ::zmk::core::LockState >(_impl_.response_type_.get_lock_state_);
  }
  return static_cast< ::zmk::core::LockState >(0);
}
inline ::zmk::core::LockState Response::get_lock_state() const {
  // @@protoc_insertion_point(field_get:zmk.core.Response.get_lock_state)
  return _internal_get_lock_state();
}
inline void Response::_internal_set_get_lock_state(::zmk::core::LockState value) {
  if (!_internal_has_get_lock_state()) {
    clear_response_type();
    set_has_get_lock_state();
  }
  _impl_.response_type_.get_lock_state_ = value;
}
inline void Response::set_get_lock_state(::zmk::core::LockState value) {
  _internal_set_get_lock_state(value);
  // @@protoc_insertion_point(field_set:zmk.core.Response.get_lock_state)
}

// bool reset_settings = 4;
inline bool Response::_internal_has_reset_settings() const {
  return response_type_case() == kResetSettings;
}
inline bool Response::has_reset_settings() const {
  return _internal_has_reset_settings();
}
inline void Response::set_has_reset_settings() {
  _impl_._oneof_case_[0] = kResetSettings;
}
inline void Response::clear_reset_settings() {
  if (_internal_has_reset_settings()) {
    _impl_.response_type_.reset_settings_ = false;
    clear_has_response_type();
  }
}
inline bool Response::_internal_reset_settings() const {
  if (_internal_has_reset_settings()) {
    return _impl_.response_type_.reset_settings_;
  }
  return false;
}
inline void Response::_internal_set_reset_settings(bool value) {
  if (!_internal_has_reset_settings()) {
    clear_response_type();
    set_has_reset_settings();
  }
  _impl_.response_type_.reset_settings_ = value;
}
inline bool Response::reset_settings() const {
  // @@protoc_insertion_point(field_get:zmk.core.Response.reset_settings)
  return _internal_reset_settings();
}
inline void Response::set_reset_settings(bool value) {
  _internal_set_reset_settings(value);
  // @@protoc_insertion_point(field_set:zmk.core.Response.reset_settings)
}

inline bool Response::has_response_type() const {
  return response_type_case() != RESPONSE_TYPE_NOT_SET;
}
inline void Response::clear_has_response_type() {
  _impl_._oneof_case_[0] = RESPONSE_TYPE_NOT_SET;
}
inline Response::ResponseTypeCase Response::response_type_case() const {
  return Response::ResponseTypeCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// GetDeviceInfoResponse

// string name = 1;
inline void GetDeviceInfoResponse::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& GetDeviceInfoResponse::name() const {
  // @@protoc_insertion_point(field_get:zmk.core.GetDeviceInfoResponse.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetDeviceInfoResponse::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:zmk.core.GetDeviceInfoResponse.name)
}
inline std::string* GetDeviceInfoResponse::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:zmk.core.GetDeviceInfoResponse.name)
  return _s;
}
inline const std::string& GetDeviceInfoResponse::_internal_name() const {
  return _impl_.name_.Get();
}
inline void GetDeviceInfoResponse::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* GetDeviceInfoResponse::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* GetDeviceInfoResponse::release_name() {
  // @@protoc_insertion_point(field_release:zmk.core.GetDeviceInfoResponse.name)
  return _impl_.name_.Release();
}
inline void GetDeviceInfoResponse::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:zmk.core.GetDeviceInfoResponse.name)
}

// bytes serial_number = 2;
inline void GetDeviceInfoResponse::clear_serial_number() {
  _impl_.serial_number_.ClearToEmpty();
}
inline const std::string& GetDeviceInfoResponse::serial_number() const {
  // @@protoc_insertion_point(field_get:zmk.core.GetDeviceInfoResponse.serial_number)
  return _internal_serial_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetDeviceInfoResponse::set_serial_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.serial_number_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:zmk.core.GetDeviceInfoResponse.serial_number)
}
inline std::string* GetDeviceInfoResponse::mutable_serial_number() {
  std::string* _s = _internal_mutable_serial_number();
  // @@protoc_insertion_point(field_mutable:zmk.core.GetDeviceInfoResponse.serial_number)
  return _s;
}
inline const std::string& GetDeviceInfoResponse::_internal_serial_number() const {
  return _impl_.serial_number_.Get();
}
inline void GetDeviceInfoResponse::_internal_set_serial_number(const std::string& value) {
  
  _impl_.serial_number_.Set(value, GetArenaForAllocation());
}
inline std::string* GetDeviceInfoResponse::_internal_mutable_serial_number() {
  
  return _impl_.serial_number_.Mutable(GetArenaForAllocation());
}
inline std::string* GetDeviceInfoResponse::release_serial_number() {
  // @@protoc_insertion_point(field_release:zmk.core.GetDeviceInfoResponse.serial_number)
  return _impl_.serial_number_.Release();
}
inline void GetDeviceInfoResponse::set_allocated_serial_number(std::string* serial_number) {
  if (serial_number != nullptr) {
    
  } else {
    
  }
  _impl_.serial_number_.SetAllocated(serial_number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.serial_number_.IsDefault()) {
    _impl_.serial_number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:zmk.core.GetDeviceInfoResponse.serial_number)
}

// -------------------------------------------------------------------

// Notification

// .zmk.core.LockState lock_state_changed = 1;
inline bool Notification::_internal_has_lock_state_changed() const {
  return notification_type_case() == kLockStateChanged;
}
inline bool Notification::has_lock_state_changed() const {
  return _internal_has_lock_state_changed();
}
inline void Notification::set_has_lock_state_changed() {
  _impl_._oneof_case_[0] = kLockStateChanged;
}
inline void Notification::clear_lock_state_changed() {
  if (_internal_has_lock_state_changed()) {
    _impl_.notification_type_.lock_state_changed_ = 0;
    clear_has_notification_type();
  }
}
inline ::zmk::core::LockState Notification::_internal_lock_state_changed() const {
  if (_internal_has_lock_state_changed()) {
    return static_cast< ::zmk::core::LockState >(_impl_.notification_type_.lock_state_changed_);
  }
  return static_cast< ::zmk::core::LockState >(0);
}
inline ::zmk::core::LockState Notification::lock_state_changed() const {
  // @@protoc_insertion_point(field_get:zmk.core.Notification.lock_state_changed)
  return _internal_lock_state_changed();
}
inline void Notification::_internal_set_lock_state_changed(::zmk::core::LockState value) {
  if (!_internal_has_lock_state_changed()) {
    clear_notification_type();
    set_has_lock_state_changed();
  }
  _impl_.notification_type_.lock_state_changed_ = value;
}
inline void Notification::set_lock_state_changed(::zmk::core::LockState value) {
  _internal_set_lock_state_changed(value);
  // @@protoc_insertion_point(field_set:zmk.core.Notification.lock_state_changed)
}

inline bool Notification::has_notification_type() const {
  return notification_type_case() != NOTIFICATION_TYPE_NOT_SET;
}
inline void Notification::clear_has_notification_type() {
  _impl_._oneof_case_[0] = NOTIFICATION_TYPE_NOT_SET;
}
inline Notification::NotificationTypeCase Notification::notification_type_case() const {
  return Notification::NotificationTypeCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace zmk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::zmk::core::LockState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zmk::core::LockState>() {
  return ::zmk::core::LockState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_core_2eproto
