// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_meta_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_meta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_meta_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_meta_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_meta_2eproto;
namespace zmk {
namespace meta {
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace meta
}  // namespace zmk
PROTOBUF_NAMESPACE_OPEN
template<> ::zmk::meta::Response* Arena::CreateMaybeMessage<::zmk::meta::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace zmk {
namespace meta {

enum ErrorConditions : int {
  GENERIC = 0,
  UNLOCK_REQUIRED = 1,
  RPC_NOT_FOUND = 2,
  MSG_DECODE_FAILED = 3,
  MSG_ENCODE_FAILED = 4,
  ErrorConditions_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ErrorConditions_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ErrorConditions_IsValid(int value);
constexpr ErrorConditions ErrorConditions_MIN = GENERIC;
constexpr ErrorConditions ErrorConditions_MAX = MSG_ENCODE_FAILED;
constexpr int ErrorConditions_ARRAYSIZE = ErrorConditions_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorConditions_descriptor();
template<typename T>
inline const std::string& ErrorConditions_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorConditions>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorConditions_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorConditions_descriptor(), enum_t_value);
}
inline bool ErrorConditions_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorConditions* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorConditions>(
    ErrorConditions_descriptor(), name, value);
}
// ===================================================================

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zmk.meta.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  enum ResponseTypeCase {
    kNoResponse = 1,
    kSimpleError = 2,
    RESPONSE_TYPE_NOT_SET = 0,
  };

  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response& from) {
    Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zmk.meta.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNoResponseFieldNumber = 1,
    kSimpleErrorFieldNumber = 2,
  };
  // bool no_response = 1;
  bool has_no_response() const;
  private:
  bool _internal_has_no_response() const;
  public:
  void clear_no_response();
  bool no_response() const;
  void set_no_response(bool value);
  private:
  bool _internal_no_response() const;
  void _internal_set_no_response(bool value);
  public:

  // .zmk.meta.ErrorConditions simple_error = 2;
  bool has_simple_error() const;
  private:
  bool _internal_has_simple_error() const;
  public:
  void clear_simple_error();
  ::zmk::meta::ErrorConditions simple_error() const;
  void set_simple_error(::zmk::meta::ErrorConditions value);
  private:
  ::zmk::meta::ErrorConditions _internal_simple_error() const;
  void _internal_set_simple_error(::zmk::meta::ErrorConditions value);
  public:

  void clear_response_type();
  ResponseTypeCase response_type_case() const;
  // @@protoc_insertion_point(class_scope:zmk.meta.Response)
 private:
  class _Internal;
  void set_has_no_response();
  void set_has_simple_error();

  inline bool has_response_type() const;
  inline void clear_has_response_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ResponseTypeUnion {
      constexpr ResponseTypeUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      bool no_response_;
      int simple_error_;
    } response_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Response

// bool no_response = 1;
inline bool Response::_internal_has_no_response() const {
  return response_type_case() == kNoResponse;
}
inline bool Response::has_no_response() const {
  return _internal_has_no_response();
}
inline void Response::set_has_no_response() {
  _impl_._oneof_case_[0] = kNoResponse;
}
inline void Response::clear_no_response() {
  if (_internal_has_no_response()) {
    _impl_.response_type_.no_response_ = false;
    clear_has_response_type();
  }
}
inline bool Response::_internal_no_response() const {
  if (_internal_has_no_response()) {
    return _impl_.response_type_.no_response_;
  }
  return false;
}
inline void Response::_internal_set_no_response(bool value) {
  if (!_internal_has_no_response()) {
    clear_response_type();
    set_has_no_response();
  }
  _impl_.response_type_.no_response_ = value;
}
inline bool Response::no_response() const {
  // @@protoc_insertion_point(field_get:zmk.meta.Response.no_response)
  return _internal_no_response();
}
inline void Response::set_no_response(bool value) {
  _internal_set_no_response(value);
  // @@protoc_insertion_point(field_set:zmk.meta.Response.no_response)
}

// .zmk.meta.ErrorConditions simple_error = 2;
inline bool Response::_internal_has_simple_error() const {
  return response_type_case() == kSimpleError;
}
inline bool Response::has_simple_error() const {
  return _internal_has_simple_error();
}
inline void Response::set_has_simple_error() {
  _impl_._oneof_case_[0] = kSimpleError;
}
inline void Response::clear_simple_error() {
  if (_internal_has_simple_error()) {
    _impl_.response_type_.simple_error_ = 0;
    clear_has_response_type();
  }
}
inline ::zmk::meta::ErrorConditions Response::_internal_simple_error() const {
  if (_internal_has_simple_error()) {
    return static_cast< ::zmk::meta::ErrorConditions >(_impl_.response_type_.simple_error_);
  }
  return static_cast< ::zmk::meta::ErrorConditions >(0);
}
inline ::zmk::meta::ErrorConditions Response::simple_error() const {
  // @@protoc_insertion_point(field_get:zmk.meta.Response.simple_error)
  return _internal_simple_error();
}
inline void Response::_internal_set_simple_error(::zmk::meta::ErrorConditions value) {
  if (!_internal_has_simple_error()) {
    clear_response_type();
    set_has_simple_error();
  }
  _impl_.response_type_.simple_error_ = value;
}
inline void Response::set_simple_error(::zmk::meta::ErrorConditions value) {
  _internal_set_simple_error(value);
  // @@protoc_insertion_point(field_set:zmk.meta.Response.simple_error)
}

inline bool Response::has_response_type() const {
  return response_type_case() != RESPONSE_TYPE_NOT_SET;
}
inline void Response::clear_has_response_type() {
  _impl_._oneof_case_[0] = RESPONSE_TYPE_NOT_SET;
}
inline Response::ResponseTypeCase Response::response_type_case() const {
  return Response::ResponseTypeCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace meta
}  // namespace zmk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::zmk::meta::ErrorConditions> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zmk::meta::ErrorConditions>() {
  return ::zmk::meta::ErrorConditions_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_meta_2eproto
