// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio.proto

#include "studio.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace zmk {
namespace studio {
PROTOBUF_CONSTEXPR Request::Request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.request_id_)*/0u
  , /*decltype(_impl_.subsystem_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestDefaultTypeInternal() {}
  union {
    Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDefaultTypeInternal _Request_default_instance_;
PROTOBUF_CONSTEXPR Response::Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseDefaultTypeInternal() {}
  union {
    Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseDefaultTypeInternal _Response_default_instance_;
PROTOBUF_CONSTEXPR RequestResponse::RequestResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.request_id_)*/0u
  , /*decltype(_impl_.subsystem_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct RequestResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestResponseDefaultTypeInternal() {}
  union {
    RequestResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestResponseDefaultTypeInternal _RequestResponse_default_instance_;
PROTOBUF_CONSTEXPR Notification::Notification(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.subsystem_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct NotificationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NotificationDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NotificationDefaultTypeInternal() {}
  union {
    Notification _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NotificationDefaultTypeInternal _Notification_default_instance_;
}  // namespace studio
}  // namespace zmk
static ::_pb::Metadata file_level_metadata_studio_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_studio_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_studio_2eproto = nullptr;

const uint32_t TableStruct_studio_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Request, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Request, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Request, _impl_.request_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Request, _impl_.subsystem_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Response, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Response, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Response, _impl_.type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::RequestResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::RequestResponse, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::RequestResponse, _impl_.request_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::zmk::studio::RequestResponse, _impl_.subsystem_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Notification, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Notification, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::zmk::studio::Notification, _impl_.subsystem_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::zmk::studio::Request)},
  { 14, -1, -1, sizeof(::zmk::studio::Response)},
  { 23, -1, -1, sizeof(::zmk::studio::RequestResponse)},
  { 38, -1, -1, sizeof(::zmk::studio::Notification)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::zmk::studio::_Request_default_instance_._instance,
  &::zmk::studio::_Response_default_instance_._instance,
  &::zmk::studio::_RequestResponse_default_instance_._instance,
  &::zmk::studio::_Notification_default_instance_._instance,
};

const char descriptor_table_protodef_studio_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014studio.proto\022\nzmk.studio\032\nmeta.proto\032\n"
  "core.proto\032\017behaviors.proto\032\014keymap.prot"
  "o\032\022led_settings.proto\032\023analog_keymap.pro"
  "to\032\rtesting.proto\"\262\002\n\007Request\022\022\n\nrequest"
  "_id\030\001 \001(\r\022!\n\004core\030\003 \001(\0132\021.zmk.core.Reque"
  "stH\000\022+\n\tbehaviors\030\004 \001(\0132\026.zmk.behaviors."
  "RequestH\000\022%\n\006keymap\030\005 \001(\0132\023.zmk.keymap.R"
  "equestH\000\0221\n\014led_settings\030@ \001(\0132\031.zmk.led"
  "_settings.RequestH\000\0223\n\ranalog_keymap\030A \001"
  "(\0132\032.zmk.analog_keymap.RequestH\000\022\'\n\007test"
  "ing\030B \001(\0132\024.zmk.testing.RequestH\000B\013\n\tsub"
  "system\"}\n\010Response\0227\n\020request_response\030\001"
  " \001(\0132\033.zmk.studio.RequestResponseH\000\0220\n\014n"
  "otification\030\002 \001(\0132\030.zmk.studio.Notificat"
  "ionH\000B\006\n\004type\"\344\002\n\017RequestResponse\022\022\n\nreq"
  "uest_id\030\001 \001(\r\022\"\n\004meta\030\002 \001(\0132\022.zmk.meta.R"
  "esponseH\000\022\"\n\004core\030\003 \001(\0132\022.zmk.core.Respo"
  "nseH\000\022,\n\tbehaviors\030\004 \001(\0132\027.zmk.behaviors"
  ".ResponseH\000\022&\n\006keymap\030\005 \001(\0132\024.zmk.keymap"
  ".ResponseH\000\0222\n\014led_settings\030@ \001(\0132\032.zmk."
  "led_settings.ResponseH\000\0224\n\ranalog_keymap"
  "\030A \001(\0132\033.zmk.analog_keymap.ResponseH\000\022(\n"
  "\007testing\030B \001(\0132\025.zmk.testing.ResponseH\000B"
  "\013\n\tsubsystem\"o\n\014Notification\022&\n\004core\030\002 \001"
  "(\0132\026.zmk.core.NotificationH\000\022*\n\006keymap\030\005"
  " \001(\0132\030.zmk.keymap.NotificationH\000B\013\n\tsubs"
  "ystemb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_studio_2eproto_deps[7] = {
  &::descriptor_table_analog_5fkeymap_2eproto,
  &::descriptor_table_behaviors_2eproto,
  &::descriptor_table_core_2eproto,
  &::descriptor_table_keymap_2eproto,
  &::descriptor_table_led_5fsettings_2eproto,
  &::descriptor_table_meta_2eproto,
  &::descriptor_table_testing_2eproto,
};
static ::_pbi::once_flag descriptor_table_studio_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_studio_2eproto = {
    false, false, 1053, descriptor_table_protodef_studio_2eproto,
    "studio.proto",
    &descriptor_table_studio_2eproto_once, descriptor_table_studio_2eproto_deps, 7, 4,
    schemas, file_default_instances, TableStruct_studio_2eproto::offsets,
    file_level_metadata_studio_2eproto, file_level_enum_descriptors_studio_2eproto,
    file_level_service_descriptors_studio_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_studio_2eproto_getter() {
  return &descriptor_table_studio_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_studio_2eproto(&descriptor_table_studio_2eproto);
namespace zmk {
namespace studio {

// ===================================================================

class Request::_Internal {
 public:
  static const ::zmk::core::Request& core(const Request* msg);
  static const ::zmk::behaviors::Request& behaviors(const Request* msg);
  static const ::zmk::keymap::Request& keymap(const Request* msg);
  static const ::zmk::led_settings::Request& led_settings(const Request* msg);
  static const ::zmk::analog_keymap::Request& analog_keymap(const Request* msg);
  static const ::zmk::testing::Request& testing(const Request* msg);
};

const ::zmk::core::Request&
Request::_Internal::core(const Request* msg) {
  return *msg->_impl_.subsystem_.core_;
}
const ::zmk::behaviors::Request&
Request::_Internal::behaviors(const Request* msg) {
  return *msg->_impl_.subsystem_.behaviors_;
}
const ::zmk::keymap::Request&
Request::_Internal::keymap(const Request* msg) {
  return *msg->_impl_.subsystem_.keymap_;
}
const ::zmk::led_settings::Request&
Request::_Internal::led_settings(const Request* msg) {
  return *msg->_impl_.subsystem_.led_settings_;
}
const ::zmk::analog_keymap::Request&
Request::_Internal::analog_keymap(const Request* msg) {
  return *msg->_impl_.subsystem_.analog_keymap_;
}
const ::zmk::testing::Request&
Request::_Internal::testing(const Request* msg) {
  return *msg->_impl_.subsystem_.testing_;
}
void Request::set_allocated_core(::zmk::core::Request* core) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (core) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(core));
    if (message_arena != submessage_arena) {
      core = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, core, submessage_arena);
    }
    set_has_core();
    _impl_.subsystem_.core_ = core;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Request.core)
}
void Request::clear_core() {
  if (_internal_has_core()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.core_;
    }
    clear_has_subsystem();
  }
}
void Request::set_allocated_behaviors(::zmk::behaviors::Request* behaviors) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (behaviors) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(behaviors));
    if (message_arena != submessage_arena) {
      behaviors = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, behaviors, submessage_arena);
    }
    set_has_behaviors();
    _impl_.subsystem_.behaviors_ = behaviors;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Request.behaviors)
}
void Request::clear_behaviors() {
  if (_internal_has_behaviors()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.behaviors_;
    }
    clear_has_subsystem();
  }
}
void Request::set_allocated_keymap(::zmk::keymap::Request* keymap) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (keymap) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(keymap));
    if (message_arena != submessage_arena) {
      keymap = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, keymap, submessage_arena);
    }
    set_has_keymap();
    _impl_.subsystem_.keymap_ = keymap;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Request.keymap)
}
void Request::clear_keymap() {
  if (_internal_has_keymap()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.keymap_;
    }
    clear_has_subsystem();
  }
}
void Request::set_allocated_led_settings(::zmk::led_settings::Request* led_settings) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (led_settings) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(led_settings));
    if (message_arena != submessage_arena) {
      led_settings = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, led_settings, submessage_arena);
    }
    set_has_led_settings();
    _impl_.subsystem_.led_settings_ = led_settings;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Request.led_settings)
}
void Request::clear_led_settings() {
  if (_internal_has_led_settings()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.led_settings_;
    }
    clear_has_subsystem();
  }
}
void Request::set_allocated_analog_keymap(::zmk::analog_keymap::Request* analog_keymap) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (analog_keymap) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(analog_keymap));
    if (message_arena != submessage_arena) {
      analog_keymap = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, analog_keymap, submessage_arena);
    }
    set_has_analog_keymap();
    _impl_.subsystem_.analog_keymap_ = analog_keymap;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Request.analog_keymap)
}
void Request::clear_analog_keymap() {
  if (_internal_has_analog_keymap()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.analog_keymap_;
    }
    clear_has_subsystem();
  }
}
void Request::set_allocated_testing(::zmk::testing::Request* testing) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (testing) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(testing));
    if (message_arena != submessage_arena) {
      testing = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, testing, submessage_arena);
    }
    set_has_testing();
    _impl_.subsystem_.testing_ = testing;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Request.testing)
}
void Request::clear_testing() {
  if (_internal_has_testing()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.testing_;
    }
    clear_has_subsystem();
  }
}
Request::Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.studio.Request)
}
Request::Request(const Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.request_id_){}
    , decltype(_impl_.subsystem_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.request_id_ = from._impl_.request_id_;
  clear_has_subsystem();
  switch (from.subsystem_case()) {
    case kCore: {
      _this->_internal_mutable_core()->::zmk::core::Request::MergeFrom(
          from._internal_core());
      break;
    }
    case kBehaviors: {
      _this->_internal_mutable_behaviors()->::zmk::behaviors::Request::MergeFrom(
          from._internal_behaviors());
      break;
    }
    case kKeymap: {
      _this->_internal_mutable_keymap()->::zmk::keymap::Request::MergeFrom(
          from._internal_keymap());
      break;
    }
    case kLedSettings: {
      _this->_internal_mutable_led_settings()->::zmk::led_settings::Request::MergeFrom(
          from._internal_led_settings());
      break;
    }
    case kAnalogKeymap: {
      _this->_internal_mutable_analog_keymap()->::zmk::analog_keymap::Request::MergeFrom(
          from._internal_analog_keymap());
      break;
    }
    case kTesting: {
      _this->_internal_mutable_testing()->::zmk::testing::Request::MergeFrom(
          from._internal_testing());
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:zmk.studio.Request)
}

inline void Request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.request_id_){0u}
    , decltype(_impl_.subsystem_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_subsystem();
}

Request::~Request() {
  // @@protoc_insertion_point(destructor:zmk.studio.Request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_subsystem()) {
    clear_subsystem();
  }
}

void Request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Request::clear_subsystem() {
// @@protoc_insertion_point(one_of_clear_start:zmk.studio.Request)
  switch (subsystem_case()) {
    case kCore: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.core_;
      }
      break;
    }
    case kBehaviors: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.behaviors_;
      }
      break;
    }
    case kKeymap: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.keymap_;
      }
      break;
    }
    case kLedSettings: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.led_settings_;
      }
      break;
    }
    case kAnalogKeymap: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.analog_keymap_;
      }
      break;
    }
    case kTesting: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.testing_;
      }
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SUBSYSTEM_NOT_SET;
}


void Request::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.studio.Request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.request_id_ = 0u;
  clear_subsystem();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.core.Request core = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_core(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.behaviors.Request behaviors = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_behaviors(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.keymap.Request keymap = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_keymap(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.led_settings.Request led_settings = 64;
      case 64:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 2)) {
          ptr = ctx->ParseMessage(_internal_mutable_led_settings(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.analog_keymap.Request analog_keymap = 65;
      case 65:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_analog_keymap(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.testing.Request testing = 66;
      case 66:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_testing(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.studio.Request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 request_id = 1;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_request_id(), target);
  }

  // .zmk.core.Request core = 3;
  if (_internal_has_core()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::core(this),
        _Internal::core(this).GetCachedSize(), target, stream);
  }

  // .zmk.behaviors.Request behaviors = 4;
  if (_internal_has_behaviors()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::behaviors(this),
        _Internal::behaviors(this).GetCachedSize(), target, stream);
  }

  // .zmk.keymap.Request keymap = 5;
  if (_internal_has_keymap()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::keymap(this),
        _Internal::keymap(this).GetCachedSize(), target, stream);
  }

  // .zmk.led_settings.Request led_settings = 64;
  if (_internal_has_led_settings()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(64, _Internal::led_settings(this),
        _Internal::led_settings(this).GetCachedSize(), target, stream);
  }

  // .zmk.analog_keymap.Request analog_keymap = 65;
  if (_internal_has_analog_keymap()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(65, _Internal::analog_keymap(this),
        _Internal::analog_keymap(this).GetCachedSize(), target, stream);
  }

  // .zmk.testing.Request testing = 66;
  if (_internal_has_testing()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(66, _Internal::testing(this),
        _Internal::testing(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.studio.Request)
  return target;
}

size_t Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.studio.Request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 request_id = 1;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_request_id());
  }

  switch (subsystem_case()) {
    // .zmk.core.Request core = 3;
    case kCore: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.core_);
      break;
    }
    // .zmk.behaviors.Request behaviors = 4;
    case kBehaviors: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.behaviors_);
      break;
    }
    // .zmk.keymap.Request keymap = 5;
    case kKeymap: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.keymap_);
      break;
    }
    // .zmk.led_settings.Request led_settings = 64;
    case kLedSettings: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.led_settings_);
      break;
    }
    // .zmk.analog_keymap.Request analog_keymap = 65;
    case kAnalogKeymap: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.analog_keymap_);
      break;
    }
    // .zmk.testing.Request testing = 66;
    case kTesting: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.testing_);
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Request::GetClassData() const { return &_class_data_; }


void Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Request*>(&to_msg);
  auto& from = static_cast<const Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.studio.Request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  switch (from.subsystem_case()) {
    case kCore: {
      _this->_internal_mutable_core()->::zmk::core::Request::MergeFrom(
          from._internal_core());
      break;
    }
    case kBehaviors: {
      _this->_internal_mutable_behaviors()->::zmk::behaviors::Request::MergeFrom(
          from._internal_behaviors());
      break;
    }
    case kKeymap: {
      _this->_internal_mutable_keymap()->::zmk::keymap::Request::MergeFrom(
          from._internal_keymap());
      break;
    }
    case kLedSettings: {
      _this->_internal_mutable_led_settings()->::zmk::led_settings::Request::MergeFrom(
          from._internal_led_settings());
      break;
    }
    case kAnalogKeymap: {
      _this->_internal_mutable_analog_keymap()->::zmk::analog_keymap::Request::MergeFrom(
          from._internal_analog_keymap());
      break;
    }
    case kTesting: {
      _this->_internal_mutable_testing()->::zmk::testing::Request::MergeFrom(
          from._internal_testing());
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request::CopyFrom(const Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.studio.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {
  return true;
}

void Request::InternalSwap(Request* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.request_id_, other->_impl_.request_id_);
  swap(_impl_.subsystem_, other->_impl_.subsystem_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_studio_2eproto_getter, &descriptor_table_studio_2eproto_once,
      file_level_metadata_studio_2eproto[0]);
}

// ===================================================================

class Response::_Internal {
 public:
  static const ::zmk::studio::RequestResponse& request_response(const Response* msg);
  static const ::zmk::studio::Notification& notification(const Response* msg);
};

const ::zmk::studio::RequestResponse&
Response::_Internal::request_response(const Response* msg) {
  return *msg->_impl_.type_.request_response_;
}
const ::zmk::studio::Notification&
Response::_Internal::notification(const Response* msg) {
  return *msg->_impl_.type_.notification_;
}
void Response::set_allocated_request_response(::zmk::studio::RequestResponse* request_response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (request_response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(request_response);
    if (message_arena != submessage_arena) {
      request_response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request_response, submessage_arena);
    }
    set_has_request_response();
    _impl_.type_.request_response_ = request_response;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Response.request_response)
}
void Response::set_allocated_notification(::zmk::studio::Notification* notification) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (notification) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(notification);
    if (message_arena != submessage_arena) {
      notification = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, notification, submessage_arena);
    }
    set_has_notification();
    _impl_.type_.notification_ = notification;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Response.notification)
}
Response::Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.studio.Response)
}
Response::Response(const Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_type();
  switch (from.type_case()) {
    case kRequestResponse: {
      _this->_internal_mutable_request_response()->::zmk::studio::RequestResponse::MergeFrom(
          from._internal_request_response());
      break;
    }
    case kNotification: {
      _this->_internal_mutable_notification()->::zmk::studio::Notification::MergeFrom(
          from._internal_notification());
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:zmk.studio.Response)
}

inline void Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_type();
}

Response::~Response() {
  // @@protoc_insertion_point(destructor:zmk.studio.Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_type()) {
    clear_type();
  }
}

void Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Response::clear_type() {
// @@protoc_insertion_point(one_of_clear_start:zmk.studio.Response)
  switch (type_case()) {
    case kRequestResponse: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.type_.request_response_;
      }
      break;
    }
    case kNotification: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.type_.notification_;
      }
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = TYPE_NOT_SET;
}


void Response::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.studio.Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_type();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .zmk.studio.RequestResponse request_response = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_request_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.studio.Notification notification = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_notification(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.studio.Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .zmk.studio.RequestResponse request_response = 1;
  if (_internal_has_request_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::request_response(this),
        _Internal::request_response(this).GetCachedSize(), target, stream);
  }

  // .zmk.studio.Notification notification = 2;
  if (_internal_has_notification()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::notification(this),
        _Internal::notification(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.studio.Response)
  return target;
}

size_t Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.studio.Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (type_case()) {
    // .zmk.studio.RequestResponse request_response = 1;
    case kRequestResponse: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.type_.request_response_);
      break;
    }
    // .zmk.studio.Notification notification = 2;
    case kNotification: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.type_.notification_);
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Response::GetClassData() const { return &_class_data_; }


void Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Response*>(&to_msg);
  auto& from = static_cast<const Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.studio.Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.type_case()) {
    case kRequestResponse: {
      _this->_internal_mutable_request_response()->::zmk::studio::RequestResponse::MergeFrom(
          from._internal_request_response());
      break;
    }
    case kNotification: {
      _this->_internal_mutable_notification()->::zmk::studio::Notification::MergeFrom(
          from._internal_notification());
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Response::CopyFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.studio.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response::IsInitialized() const {
  return true;
}

void Response::InternalSwap(Response* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_studio_2eproto_getter, &descriptor_table_studio_2eproto_once,
      file_level_metadata_studio_2eproto[1]);
}

// ===================================================================

class RequestResponse::_Internal {
 public:
  static const ::zmk::meta::Response& meta(const RequestResponse* msg);
  static const ::zmk::core::Response& core(const RequestResponse* msg);
  static const ::zmk::behaviors::Response& behaviors(const RequestResponse* msg);
  static const ::zmk::keymap::Response& keymap(const RequestResponse* msg);
  static const ::zmk::led_settings::Response& led_settings(const RequestResponse* msg);
  static const ::zmk::analog_keymap::Response& analog_keymap(const RequestResponse* msg);
  static const ::zmk::testing::Response& testing(const RequestResponse* msg);
};

const ::zmk::meta::Response&
RequestResponse::_Internal::meta(const RequestResponse* msg) {
  return *msg->_impl_.subsystem_.meta_;
}
const ::zmk::core::Response&
RequestResponse::_Internal::core(const RequestResponse* msg) {
  return *msg->_impl_.subsystem_.core_;
}
const ::zmk::behaviors::Response&
RequestResponse::_Internal::behaviors(const RequestResponse* msg) {
  return *msg->_impl_.subsystem_.behaviors_;
}
const ::zmk::keymap::Response&
RequestResponse::_Internal::keymap(const RequestResponse* msg) {
  return *msg->_impl_.subsystem_.keymap_;
}
const ::zmk::led_settings::Response&
RequestResponse::_Internal::led_settings(const RequestResponse* msg) {
  return *msg->_impl_.subsystem_.led_settings_;
}
const ::zmk::analog_keymap::Response&
RequestResponse::_Internal::analog_keymap(const RequestResponse* msg) {
  return *msg->_impl_.subsystem_.analog_keymap_;
}
const ::zmk::testing::Response&
RequestResponse::_Internal::testing(const RequestResponse* msg) {
  return *msg->_impl_.subsystem_.testing_;
}
void RequestResponse::set_allocated_meta(::zmk::meta::Response* meta) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (meta) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(meta));
    if (message_arena != submessage_arena) {
      meta = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    set_has_meta();
    _impl_.subsystem_.meta_ = meta;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.RequestResponse.meta)
}
void RequestResponse::clear_meta() {
  if (_internal_has_meta()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.meta_;
    }
    clear_has_subsystem();
  }
}
void RequestResponse::set_allocated_core(::zmk::core::Response* core) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (core) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(core));
    if (message_arena != submessage_arena) {
      core = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, core, submessage_arena);
    }
    set_has_core();
    _impl_.subsystem_.core_ = core;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.RequestResponse.core)
}
void RequestResponse::clear_core() {
  if (_internal_has_core()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.core_;
    }
    clear_has_subsystem();
  }
}
void RequestResponse::set_allocated_behaviors(::zmk::behaviors::Response* behaviors) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (behaviors) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(behaviors));
    if (message_arena != submessage_arena) {
      behaviors = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, behaviors, submessage_arena);
    }
    set_has_behaviors();
    _impl_.subsystem_.behaviors_ = behaviors;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.RequestResponse.behaviors)
}
void RequestResponse::clear_behaviors() {
  if (_internal_has_behaviors()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.behaviors_;
    }
    clear_has_subsystem();
  }
}
void RequestResponse::set_allocated_keymap(::zmk::keymap::Response* keymap) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (keymap) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(keymap));
    if (message_arena != submessage_arena) {
      keymap = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, keymap, submessage_arena);
    }
    set_has_keymap();
    _impl_.subsystem_.keymap_ = keymap;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.RequestResponse.keymap)
}
void RequestResponse::clear_keymap() {
  if (_internal_has_keymap()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.keymap_;
    }
    clear_has_subsystem();
  }
}
void RequestResponse::set_allocated_led_settings(::zmk::led_settings::Response* led_settings) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (led_settings) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(led_settings));
    if (message_arena != submessage_arena) {
      led_settings = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, led_settings, submessage_arena);
    }
    set_has_led_settings();
    _impl_.subsystem_.led_settings_ = led_settings;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.RequestResponse.led_settings)
}
void RequestResponse::clear_led_settings() {
  if (_internal_has_led_settings()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.led_settings_;
    }
    clear_has_subsystem();
  }
}
void RequestResponse::set_allocated_analog_keymap(::zmk::analog_keymap::Response* analog_keymap) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (analog_keymap) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(analog_keymap));
    if (message_arena != submessage_arena) {
      analog_keymap = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, analog_keymap, submessage_arena);
    }
    set_has_analog_keymap();
    _impl_.subsystem_.analog_keymap_ = analog_keymap;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.RequestResponse.analog_keymap)
}
void RequestResponse::clear_analog_keymap() {
  if (_internal_has_analog_keymap()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.analog_keymap_;
    }
    clear_has_subsystem();
  }
}
void RequestResponse::set_allocated_testing(::zmk::testing::Response* testing) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (testing) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(testing));
    if (message_arena != submessage_arena) {
      testing = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, testing, submessage_arena);
    }
    set_has_testing();
    _impl_.subsystem_.testing_ = testing;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.RequestResponse.testing)
}
void RequestResponse::clear_testing() {
  if (_internal_has_testing()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.testing_;
    }
    clear_has_subsystem();
  }
}
RequestResponse::RequestResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.studio.RequestResponse)
}
RequestResponse::RequestResponse(const RequestResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RequestResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.request_id_){}
    , decltype(_impl_.subsystem_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.request_id_ = from._impl_.request_id_;
  clear_has_subsystem();
  switch (from.subsystem_case()) {
    case kMeta: {
      _this->_internal_mutable_meta()->::zmk::meta::Response::MergeFrom(
          from._internal_meta());
      break;
    }
    case kCore: {
      _this->_internal_mutable_core()->::zmk::core::Response::MergeFrom(
          from._internal_core());
      break;
    }
    case kBehaviors: {
      _this->_internal_mutable_behaviors()->::zmk::behaviors::Response::MergeFrom(
          from._internal_behaviors());
      break;
    }
    case kKeymap: {
      _this->_internal_mutable_keymap()->::zmk::keymap::Response::MergeFrom(
          from._internal_keymap());
      break;
    }
    case kLedSettings: {
      _this->_internal_mutable_led_settings()->::zmk::led_settings::Response::MergeFrom(
          from._internal_led_settings());
      break;
    }
    case kAnalogKeymap: {
      _this->_internal_mutable_analog_keymap()->::zmk::analog_keymap::Response::MergeFrom(
          from._internal_analog_keymap());
      break;
    }
    case kTesting: {
      _this->_internal_mutable_testing()->::zmk::testing::Response::MergeFrom(
          from._internal_testing());
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:zmk.studio.RequestResponse)
}

inline void RequestResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.request_id_){0u}
    , decltype(_impl_.subsystem_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_subsystem();
}

RequestResponse::~RequestResponse() {
  // @@protoc_insertion_point(destructor:zmk.studio.RequestResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RequestResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_subsystem()) {
    clear_subsystem();
  }
}

void RequestResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RequestResponse::clear_subsystem() {
// @@protoc_insertion_point(one_of_clear_start:zmk.studio.RequestResponse)
  switch (subsystem_case()) {
    case kMeta: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.meta_;
      }
      break;
    }
    case kCore: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.core_;
      }
      break;
    }
    case kBehaviors: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.behaviors_;
      }
      break;
    }
    case kKeymap: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.keymap_;
      }
      break;
    }
    case kLedSettings: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.led_settings_;
      }
      break;
    }
    case kAnalogKeymap: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.analog_keymap_;
      }
      break;
    }
    case kTesting: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.testing_;
      }
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SUBSYSTEM_NOT_SET;
}


void RequestResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.studio.RequestResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.request_id_ = 0u;
  clear_subsystem();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RequestResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.meta.Response meta = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_meta(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.core.Response core = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_core(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.behaviors.Response behaviors = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_behaviors(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.keymap.Response keymap = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_keymap(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.led_settings.Response led_settings = 64;
      case 64:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 2)) {
          ptr = ctx->ParseMessage(_internal_mutable_led_settings(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.analog_keymap.Response analog_keymap = 65;
      case 65:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_analog_keymap(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.testing.Response testing = 66;
      case 66:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_testing(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RequestResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.studio.RequestResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 request_id = 1;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_request_id(), target);
  }

  // .zmk.meta.Response meta = 2;
  if (_internal_has_meta()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::meta(this),
        _Internal::meta(this).GetCachedSize(), target, stream);
  }

  // .zmk.core.Response core = 3;
  if (_internal_has_core()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::core(this),
        _Internal::core(this).GetCachedSize(), target, stream);
  }

  // .zmk.behaviors.Response behaviors = 4;
  if (_internal_has_behaviors()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::behaviors(this),
        _Internal::behaviors(this).GetCachedSize(), target, stream);
  }

  // .zmk.keymap.Response keymap = 5;
  if (_internal_has_keymap()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::keymap(this),
        _Internal::keymap(this).GetCachedSize(), target, stream);
  }

  // .zmk.led_settings.Response led_settings = 64;
  if (_internal_has_led_settings()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(64, _Internal::led_settings(this),
        _Internal::led_settings(this).GetCachedSize(), target, stream);
  }

  // .zmk.analog_keymap.Response analog_keymap = 65;
  if (_internal_has_analog_keymap()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(65, _Internal::analog_keymap(this),
        _Internal::analog_keymap(this).GetCachedSize(), target, stream);
  }

  // .zmk.testing.Response testing = 66;
  if (_internal_has_testing()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(66, _Internal::testing(this),
        _Internal::testing(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.studio.RequestResponse)
  return target;
}

size_t RequestResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.studio.RequestResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 request_id = 1;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_request_id());
  }

  switch (subsystem_case()) {
    // .zmk.meta.Response meta = 2;
    case kMeta: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.meta_);
      break;
    }
    // .zmk.core.Response core = 3;
    case kCore: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.core_);
      break;
    }
    // .zmk.behaviors.Response behaviors = 4;
    case kBehaviors: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.behaviors_);
      break;
    }
    // .zmk.keymap.Response keymap = 5;
    case kKeymap: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.keymap_);
      break;
    }
    // .zmk.led_settings.Response led_settings = 64;
    case kLedSettings: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.led_settings_);
      break;
    }
    // .zmk.analog_keymap.Response analog_keymap = 65;
    case kAnalogKeymap: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.analog_keymap_);
      break;
    }
    // .zmk.testing.Response testing = 66;
    case kTesting: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.testing_);
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RequestResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RequestResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RequestResponse::GetClassData() const { return &_class_data_; }


void RequestResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RequestResponse*>(&to_msg);
  auto& from = static_cast<const RequestResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.studio.RequestResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  switch (from.subsystem_case()) {
    case kMeta: {
      _this->_internal_mutable_meta()->::zmk::meta::Response::MergeFrom(
          from._internal_meta());
      break;
    }
    case kCore: {
      _this->_internal_mutable_core()->::zmk::core::Response::MergeFrom(
          from._internal_core());
      break;
    }
    case kBehaviors: {
      _this->_internal_mutable_behaviors()->::zmk::behaviors::Response::MergeFrom(
          from._internal_behaviors());
      break;
    }
    case kKeymap: {
      _this->_internal_mutable_keymap()->::zmk::keymap::Response::MergeFrom(
          from._internal_keymap());
      break;
    }
    case kLedSettings: {
      _this->_internal_mutable_led_settings()->::zmk::led_settings::Response::MergeFrom(
          from._internal_led_settings());
      break;
    }
    case kAnalogKeymap: {
      _this->_internal_mutable_analog_keymap()->::zmk::analog_keymap::Response::MergeFrom(
          from._internal_analog_keymap());
      break;
    }
    case kTesting: {
      _this->_internal_mutable_testing()->::zmk::testing::Response::MergeFrom(
          from._internal_testing());
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RequestResponse::CopyFrom(const RequestResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.studio.RequestResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestResponse::IsInitialized() const {
  return true;
}

void RequestResponse::InternalSwap(RequestResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.request_id_, other->_impl_.request_id_);
  swap(_impl_.subsystem_, other->_impl_.subsystem_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata RequestResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_studio_2eproto_getter, &descriptor_table_studio_2eproto_once,
      file_level_metadata_studio_2eproto[2]);
}

// ===================================================================

class Notification::_Internal {
 public:
  static const ::zmk::core::Notification& core(const Notification* msg);
  static const ::zmk::keymap::Notification& keymap(const Notification* msg);
};

const ::zmk::core::Notification&
Notification::_Internal::core(const Notification* msg) {
  return *msg->_impl_.subsystem_.core_;
}
const ::zmk::keymap::Notification&
Notification::_Internal::keymap(const Notification* msg) {
  return *msg->_impl_.subsystem_.keymap_;
}
void Notification::set_allocated_core(::zmk::core::Notification* core) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (core) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(core));
    if (message_arena != submessage_arena) {
      core = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, core, submessage_arena);
    }
    set_has_core();
    _impl_.subsystem_.core_ = core;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Notification.core)
}
void Notification::clear_core() {
  if (_internal_has_core()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.core_;
    }
    clear_has_subsystem();
  }
}
void Notification::set_allocated_keymap(::zmk::keymap::Notification* keymap) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_subsystem();
  if (keymap) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(keymap));
    if (message_arena != submessage_arena) {
      keymap = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, keymap, submessage_arena);
    }
    set_has_keymap();
    _impl_.subsystem_.keymap_ = keymap;
  }
  // @@protoc_insertion_point(field_set_allocated:zmk.studio.Notification.keymap)
}
void Notification::clear_keymap() {
  if (_internal_has_keymap()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.subsystem_.keymap_;
    }
    clear_has_subsystem();
  }
}
Notification::Notification(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:zmk.studio.Notification)
}
Notification::Notification(const Notification& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Notification* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.subsystem_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_subsystem();
  switch (from.subsystem_case()) {
    case kCore: {
      _this->_internal_mutable_core()->::zmk::core::Notification::MergeFrom(
          from._internal_core());
      break;
    }
    case kKeymap: {
      _this->_internal_mutable_keymap()->::zmk::keymap::Notification::MergeFrom(
          from._internal_keymap());
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:zmk.studio.Notification)
}

inline void Notification::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.subsystem_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_subsystem();
}

Notification::~Notification() {
  // @@protoc_insertion_point(destructor:zmk.studio.Notification)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Notification::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_subsystem()) {
    clear_subsystem();
  }
}

void Notification::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Notification::clear_subsystem() {
// @@protoc_insertion_point(one_of_clear_start:zmk.studio.Notification)
  switch (subsystem_case()) {
    case kCore: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.core_;
      }
      break;
    }
    case kKeymap: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.subsystem_.keymap_;
      }
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SUBSYSTEM_NOT_SET;
}


void Notification::Clear() {
// @@protoc_insertion_point(message_clear_start:zmk.studio.Notification)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_subsystem();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Notification::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .zmk.core.Notification core = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_core(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .zmk.keymap.Notification keymap = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_keymap(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Notification::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zmk.studio.Notification)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .zmk.core.Notification core = 2;
  if (_internal_has_core()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::core(this),
        _Internal::core(this).GetCachedSize(), target, stream);
  }

  // .zmk.keymap.Notification keymap = 5;
  if (_internal_has_keymap()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::keymap(this),
        _Internal::keymap(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zmk.studio.Notification)
  return target;
}

size_t Notification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zmk.studio.Notification)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (subsystem_case()) {
    // .zmk.core.Notification core = 2;
    case kCore: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.core_);
      break;
    }
    // .zmk.keymap.Notification keymap = 5;
    case kKeymap: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.subsystem_.keymap_);
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Notification::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Notification::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Notification::GetClassData() const { return &_class_data_; }


void Notification::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Notification*>(&to_msg);
  auto& from = static_cast<const Notification&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zmk.studio.Notification)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.subsystem_case()) {
    case kCore: {
      _this->_internal_mutable_core()->::zmk::core::Notification::MergeFrom(
          from._internal_core());
      break;
    }
    case kKeymap: {
      _this->_internal_mutable_keymap()->::zmk::keymap::Notification::MergeFrom(
          from._internal_keymap());
      break;
    }
    case SUBSYSTEM_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Notification::CopyFrom(const Notification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zmk.studio.Notification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Notification::IsInitialized() const {
  return true;
}

void Notification::InternalSwap(Notification* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.subsystem_, other->_impl_.subsystem_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Notification::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_studio_2eproto_getter, &descriptor_table_studio_2eproto_once,
      file_level_metadata_studio_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace studio
}  // namespace zmk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::zmk::studio::Request*
Arena::CreateMaybeMessage< ::zmk::studio::Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::studio::Request >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::studio::Response*
Arena::CreateMaybeMessage< ::zmk::studio::Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::studio::Response >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::studio::RequestResponse*
Arena::CreateMaybeMessage< ::zmk::studio::RequestResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::studio::RequestResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::zmk::studio::Notification*
Arena::CreateMaybeMessage< ::zmk::studio::Notification >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zmk::studio::Notification >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
